//  Copyright 2024 Helios Contributors
//    
//  Helios is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  Helios is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.

namespace GadrocsWorkshop.Helios.Interfaces.DCS.C130J
{
    internal class Commands
    {
        internal enum Button
        {
            Button_1 = 3001,
            Button_2 = 3002,
            Button_3 = 3003,
            Button_4 = 3004,
            Button_5 = 3005,
            Button_6 = 3006,
            Button_7 = 3007,
            Button_8 = 3008,
            Button_9 = 3009,
            Button_10 = 3010,
            Button_11 = 3011,
            Button_12 = 3012,
            Button_13 = 3013,
            Button_14 = 3014,
            Button_15 = 3015,
            Button_16 = 3016,
            Button_17 = 3017,
            Button_18 = 3018,
            Button_19 = 3019,
            Button_20 = 3020,
            Button_21 = 3021,
            Button_22 = 3022,
            Button_23 = 3023,
            Button_24 = 3024,
            Button_25 = 3025,
            Button_26 = 3026,
            Button_27 = 3027,
            Button_28 = 3028,
            Button_29 = 3029,
            Button_30 = 3030,
            Button_31 = 3031,
            Button_32 = 3032,
            Button_33 = 3033,
            Button_34 = 3034,
            Button_35 = 3035,
            Button_36 = 3036,
            Button_37 = 3037,
            Button_38 = 3038,
            Button_39 = 3039,
            Button_40 = 3040,
            Button_41 = 3041,
            Button_42 = 3042,
            Button_43 = 3043,
            Button_44 = 3044,
            Button_45 = 3045,
            Button_46 = 3046,
            Button_47 = 3047,
            Button_48 = 3048,
            Button_49 = 3049,
            Button_50 = 3050,
            Button_51 = 3051,
            Button_52 = 3052,
            Button_53 = 3053,
            Button_54 = 3054,
            Button_55 = 3055,
            Button_56 = 3056,
            Button_57 = 3057,
            Button_58 = 3058,
            Button_59 = 3059,
            Button_60 = 3060,
            Button_61 = 3061,
            Button_62 = 3062,
            Button_63 = 3063,
            Button_64 = 3064,
            Button_65 = 3065,
            Button_66 = 3066,
            Button_67 = 3067,
            Button_68 = 3068,
            Button_69 = 3069,
            Button_70 = 3070,
            Button_71 = 3071,
            Button_72 = 3072,
            Button_73 = 3073,
            Button_74 = 3074,
            Button_75 = 3075,
            Button_76 = 3076,
            Button_77 = 3077,
            Button_78 = 3078,
            Button_79 = 3079,
            Button_80 = 3080,
            Button_81 = 3081,
            Button_82 = 3082,
            Button_83 = 3083,
            Button_84 = 3084,
            Button_85 = 3085,
            Button_86 = 3086,
            Button_87 = 3087,
            Button_88 = 3088,
            Button_89 = 3089,
            Button_90 = 3090,
            Button_91 = 3091,
            Button_92 = 3092,
            Button_93 = 3093,
            Button_94 = 3094,
            Button_95 = 3095,
            Button_96 = 3096,
            Button_97 = 3097,
            Button_98 = 3098,
            Button_99 = 3099,
            Button_100 = 3100,
            Button_101 = 3101,
            Button_102 = 3102,
            Button_103 = 3103,
            Button_104 = 3104,
            Button_105 = 3105,
            Button_106 = 3106,
            Button_107 = 3107,
            Button_108 = 3108,
            Button_109 = 3109,
            Button_110 = 3110,
            Button_111 = 3111,
            Button_112 = 3112,
            Button_113 = 3113,
            Button_114 = 3114,
            Button_115 = 3115,
            Button_116 = 3116,
            Button_117 = 3117,
            Button_118 = 3118,
            Button_119 = 3119,
            Button_120 = 3120,
            Button_121 = 3121,
            Button_122 = 3122,
            Button_123 = 3123,
            Button_124 = 3124,
            Button_125 = 3125,
            Button_126 = 3126,
            Button_127 = 3127,
            Button_128 = 3128,
            Button_129 = 3129,
            Button_130 = 3130,
            Button_131 = 3131,
            Button_132 = 3132,
            Button_133 = 3133,
            Button_134 = 3134,
            Button_135 = 3135,
            Button_136 = 3136,
            Button_137 = 3137,
            Button_138 = 3138,
            Button_139 = 3139,
            Button_140 = 3140,
            Button_141 = 3141,
            Button_142 = 3142,
            Button_143 = 3143,
            Button_144 = 3144,
            Button_145 = 3145,
            Button_146 = 3146,
            Button_147 = 3147,
            Button_148 = 3148,
            Button_149 = 3149,
            Button_150 = 3150,
            Button_151 = 3151,
            Button_152 = 3152,
            Button_153 = 3153,
            Button_154 = 3154,
            Button_155 = 3155,
            Button_156 = 3156,
            Button_157 = 3157,
            Button_158 = 3158,
            Button_159 = 3159,
            Button_160 = 3160,
            Button_161 = 3161,
            Button_162 = 3162,
            Button_163 = 3163,
            Button_164 = 3164,
            Button_165 = 3165,
            Button_166 = 3166,
            Button_167 = 3167,
            Button_168 = 3168,
            Button_169 = 3169,
            Button_170 = 3170,
            Button_171 = 3171,
            Button_172 = 3172,
            Button_173 = 3173,
            Button_174 = 3174,
            Button_175 = 3175,
            Button_176 = 3176,
            Button_177 = 3177,
            Button_178 = 3178,
            Button_179 = 3179,
            Button_180 = 3180,
            Button_181 = 3181,
            Button_182 = 3182,
            Button_183 = 3183,
            Button_184 = 3184,
            Button_185 = 3185,
            Button_186 = 3186,
            Button_187 = 3187,
            Button_188 = 3188,
            Button_189 = 3189,
            Button_190 = 3190,
            Button_191 = 3191,
            Button_192 = 3192,
            Button_193 = 3193,
            Button_194 = 3194,
            Button_195 = 3195,
            Button_196 = 3196,
            Button_197 = 3197,
            Button_198 = 3198,
            Button_199 = 3199,
            Button_200 = 3200,
            Button_201 = 3201,
            Button_202 = 3202,
            Button_203 = 3203,
            Button_204 = 3204,
            Button_205 = 3205,
            Button_206 = 3206,
            Button_207 = 3207,
            Button_208 = 3208,
            Button_209 = 3209,
            Button_210 = 3210,
            Button_211 = 3211,
            Button_212 = 3212,
            Button_213 = 3213,
            Button_214 = 3214,
            Button_215 = 3215,
            Button_216 = 3216,
            Button_217 = 3217,
            Button_218 = 3218,
            Button_219 = 3219,
            Button_220 = 3220,
            Button_221 = 3221,
            Button_222 = 3222,
            Button_223 = 3223,
            Button_224 = 3224,
            Button_225 = 3225,
            Button_226 = 3226,
            Button_227 = 3227,
            Button_228 = 3228,
            Button_229 = 3229,
            Button_230 = 3230,
            Button_231 = 3231,
            Button_232 = 3232,
            Button_233 = 3233,
            Button_234 = 3234,
            Button_235 = 3235,
            Button_236 = 3236,
            Button_237 = 3237,
            Button_238 = 3238,
            Button_239 = 3239,
            Button_240 = 3240,
            Button_241 = 3241,
            Button_242 = 3242,
            Button_243 = 3243,
            Button_244 = 3244,
            Button_245 = 3245,
            Button_246 = 3246,
            Button_247 = 3247,
            Button_248 = 3248,
            Button_249 = 3249,
            Button_250 = 3250,
            Button_251 = 3251,
            Button_252 = 3252,
            Button_253 = 3253,
            Button_254 = 3254,
            Button_255 = 3255,
            Button_256 = 3256,
            Button_257 = 3257,
            Button_258 = 3258,
            Button_259 = 3259,
            Button_260 = 3260,
            Button_261 = 3261,
            Button_262 = 3262,
            Button_263 = 3263,
            Button_264 = 3264,
            Button_265 = 3265,
            Button_266 = 3266,
            Button_267 = 3267,
            Button_268 = 3268,
            Button_269 = 3269,
            Button_270 = 3270,
            Button_271 = 3271,
            Button_272 = 3272,
            Button_273 = 3273,
            Button_274 = 3274,
            Button_275 = 3275,
            Button_276 = 3276,
            Button_277 = 3277,
            Button_278 = 3278,
            Button_279 = 3279,
            Button_280 = 3280,
            Button_281 = 3281,
            Button_282 = 3282,
            Button_283 = 3283,
            Button_284 = 3284,
            Button_285 = 3285,
            Button_286 = 3286,
            Button_287 = 3287,
            Button_288 = 3288,
            Button_289 = 3289,
            Button_290 = 3290,
            Button_291 = 3291,
            Button_292 = 3292,
            Button_293 = 3293,
            Button_294 = 3294,
            Button_295 = 3295,
            Button_296 = 3296,
            Button_297 = 3297,
            Button_298 = 3298,
            Button_299 = 3299,
            Button_300 = 3300,
        }
        internal enum PILOT_COCKPIT_INTERFACE
        {
            HDG_SET = 3001,
            CRS_SET,
            HDG_RESET,
            CRS_RESET,
            stopwatch_mode,
            go_around,
            kbd_heading,
            kbd_course,
            shade_show_hide,
            shade_rotate,
            hdg_rotary,
            crs_rotary,
            pfd_priority,
            coffee_cup,
            transmit,
            hud_declutter,
        }
        internal enum COPILOT_COCKPIT_INTERFACE
        {
            HDG_SET = 3001,
            CRS_SET,
            HDG_RESET,
            CRS_RESET,
            stopwatch_mode,
            go_around,
            kbd_heading,
            kbd_course,
            shade_show_hide,
            shade_rotate,
            hdg_rotary,
            crs_rotary,
            pfd_priority,
            coffee_cup,
            transmit,
            hud_declutter
        }
        internal enum REF_MODE_PANEL
        {
            ref_select = 3001,
            ref_set,
            ref_set_press,
            ref_mode_kbd,
            alt_alert_set,
            alt_alert_reset,
            baro_set,
            baro_ISA_set,

            master_warning,
            master_caution,
            set_abs_ref,
            kbd_ref_knob,
            sync_alt_ref,
            sync_hp,
            sync_radalt,
            sync_fpa,
            sync_ias,
            sync_mins,
            sync_baro,

        }
        internal enum PILOT_AP
        {
            alt_hold = 3001,
            alt_sel,
            hdg_sel,
            nav_sel,
            appr_sel,
            vs_hold_sel,
            ias_sel,
            caps_sel,
            autothrottle_sel,
            blank_sel,
            afcs_toggle_p,
            afcs_toggle_cp,
            afcs_pitch,
            afcs_lat,
            afcs_pitch_knob,
            afcs_lat_knob,
            ap_off,
            syn,
            ap_off_nosync_p,
            ap_off_nosync_cp,

            cp_alt_hold,
            cp_alt_sel,
            cp_hdg_sel,
            cp_nav_sel,
            cp_appr_sel,
            cp_vs_hold_sel,
            cp_ias_sel,
            cp_caps_sel,
            cp_autothrottle_sel,
            cp_blank_sel,

            afcs_kbd_pitch,
            afcs_kbd_lat,
            afcs_reset_wheel,
            pitch_syn_sync,
            at_disconnect_l,
            at_disconnect_r,
            afcs_reset_wheel_lat,
            afcs_reset_wheel_pitch,

            afcs_p_on_off,
            afcs_cp_on_off,

            afcs_lat_sync,
            afcs_ptc_sync,

        }
        internal enum LIGHTING_PANELS
        {
            landing_right = 3001,
            landing_left,

            landing_right_position,
            landing_left_position,

            display_master,

            taxi_light_wheels,
            taxi_light_wings,

            ext_master,
            ext_nav,
            ext_dim,
            ext_covert,
            ext_strobe_top,
            ext_strobe_btm,
            ext_strobe_test,
            ext_ledge,
            covert_form_brt,
            dome_light,
            p_circuit_breaker,
            cp_circuit_breaker,
            pilot_side_flood,
            copilot_side_flood,
            overhead,
            standby_lights,

            copilot_display_master,
            floor,
            ovh_flood,

            cp_ctrl_cnsl,
            cp_lamp_test,
            master_mode,
            ann_dim_brt,
            pilot_side_panel,
            copilot_side_panel,

            landing_light_all,
            landing_motor_all,
            taxi_light_all,

        }
        internal enum AIRCOND
        {
            flt_power = 3001,
            cargo_power,
            flt_temp,
            cargo_temp,
            flt_man,
            cargo_man,
            cross_flow_value_man,
            cross_flow_valve_open,
            underfloor,
            press_valve_man_open,
            emerg_press_dump,
            press_mode,
            emerg_press_dump_guard,
            auto_rate,
            landing_press,
            landing_press_abs,

            sync_auto_rate,
            sync_landing_press,
            sync_cabin_press,
            sync_cargo_temp,
            sync_cabin_temp,
            sync_rate_abs,
            sync_cargo_temp_tgt,
            sync_cabin_temp_tgt,

            flt_power_on,
            flt_power_off,
            cargo_power_on,
            cargo_power_off,

            pilot_regulator_pct,
            emerg_pilot_regulator,
            pilot_oxy_supply,

            copilot_regulator_pct,
            emerg_copilot_regulator,
            copilot_oxy_supply,
            landing_press_viz,
            pilot_oxy_flow,
            copilot_oxy_flow,
        }
        internal enum P_CNI
        {
            SELECT_1 = 3001,
            SELECT_2,
            SELECT_3,
            SELECT_4,
            SELECT_5,
            SELECT_6,
            SELECT_7,
            SELECT_8,
            SELECT_9,
            SELECT_10,
            SELECT_11,
            SELECT_12,

            COMM_TUNE,
            TOLD,
            NAV_CTRL,
            INDEX,
            MC_INDX,
            DIR,
            LEGS,
            MARK,
            IFF,
            NAV_TUNE,
            MSN,
            CAPS,

            EXEC,
            NEXT,
            PREV,
            DEL,
            CLR,

            KBD_0,
            KBD_1,
            KBD_2,
            KBD_3,
            KBD_4,
            KBD_5,
            KBD_6,
            KBD_7,
            KBD_8,
            KBD_9,
            KBD_DOT,
            KBD_PLUSMINUS,

            KBD_A,
            KBD_B,
            KBD_C,
            KBD_D,
            KBD_E,
            KBD_F,
            KBD_G,
            KBD_H,
            KBD_I,
            KBD_J,
            KBD_K,
            KBD_L,
            KBD_M,
            KBD_N,
            KBD_O,
            KBD_P,
            KBD_Q,
            KBD_R,
            KBD_S,
            KBD_T,
            KBD_U,
            KBD_V,
            KBD_W,
            KBD_X,
            KBD_Y,
            KBD_Z,
            KBD_SLASH,

            KBD_SPACE,

            BRT_UP,
            BRT_DN,

            sync_page,
            sync_mode,
            clear_full_scratch,

        }
        internal enum C_CNI
        {
            SELECT_1 = 3001,
            SELECT_2,
            SELECT_3,
            SELECT_4,
            SELECT_5,
            SELECT_6,
            SELECT_7,
            SELECT_8,
            SELECT_9,
            SELECT_10,
            SELECT_11,
            SELECT_12,

            COMM_TUNE,
            TOLD,
            NAV_CTRL,
            INDEX,
            MC_INDX,
            DIR,
            LEGS,
            MARK,
            IFF,
            NAV_TUNE,
            MSN,
            CAPS,

            EXEC,
            NEXT,
            PREV,
            DEL,
            CLR,

            KBD_0,
            KBD_1,
            KBD_2,
            KBD_3,
            KBD_4,
            KBD_5,
            KBD_6,
            KBD_7,
            KBD_8,
            KBD_9,
            KBD_DOT,
            KBD_PLUSMINUS,

            KBD_A,
            KBD_B,
            KBD_C,
            KBD_D,
            KBD_E,
            KBD_F,
            KBD_G,
            KBD_H,
            KBD_I,
            KBD_J,
            KBD_K,
            KBD_L,
            KBD_M,
            KBD_N,
            KBD_O,
            KBD_P,
            KBD_Q,
            KBD_R,
            KBD_S,
            KBD_T,
            KBD_U,
            KBD_V,
            KBD_W,
            KBD_X,
            KBD_Y,
            KBD_Z,
            KBD_SLASH,

            KBD_SPACE,

            BRT_UP,
            BRT_DN,

            sync_page,
            sync_mode,
            clear_full_scratch,

        }
        internal enum AC_CNI
        {
            SELECT_1 = 3001,
            SELECT_2,
            SELECT_3,
            SELECT_4,
            SELECT_5,
            SELECT_6,
            SELECT_7,
            SELECT_8,
            SELECT_9,
            SELECT_10,
            SELECT_11,
            SELECT_12,

            COMM_TUNE,
            TOLD,
            NAV_CTRL,
            INDEX,
            MC_INDX,
            DIR,
            LEGS,
            MARK,
            IFF,
            NAV_TUNE,
            MSN,
            CAPS,

            EXEC,
            NEXT,
            PREV,
            DEL,
            CLR,

            KBD_0,
            KBD_1,
            KBD_2,
            KBD_3,
            KBD_4,
            KBD_5,
            KBD_6,
            KBD_7,
            KBD_8,
            KBD_9,
            KBD_DOT,
            KBD_PLUSMINUS,

            KBD_A,
            KBD_B,
            KBD_C,
            KBD_D,
            KBD_E,
            KBD_F,
            KBD_G,
            KBD_H,
            KBD_I,
            KBD_J,
            KBD_K,
            KBD_L,
            KBD_M,
            KBD_N,
            KBD_O,
            KBD_P,
            KBD_Q,
            KBD_R,
            KBD_S,
            KBD_T,
            KBD_U,
            KBD_V,
            KBD_W,
            KBD_X,
            KBD_Y,
            KBD_Z,
            KBD_SLASH,

            KBD_SPACE,

            BRT_UP,
            BRT_DN,

            sync_page,
            sync_mode,
            clear_full_scratch,

        }
        internal enum CNE
        {
            num_0 = 3001,
            num_1,
            num_2,
            num_3,
            num_4,
            num_5,
            num_6,
            num_7,
            num_8,
            num_9,
            num_dot,

            clr,

            selkey1,
            selkey2,
            selkey3,
            selkey4,
            selkey5,
            selkey6,
            selkey7,
            selkey8,

            comm,
            nav,
            ecb,

            brightness,
            brightness_down,

        }
        internal enum JOYSTICK
        {
	        // roll = counter();
            PedalLeftBrake = 4001,
            PedalRightBrake,

            throttle1,
            throttle2,
            throttle3,
            throttle4,

            LeftThrottle,
            RightThrottle,

            BothThrottle,

            PedalBothBrake,
            NoseWheelSteering,

            pitch_trim,
            roll_trim,
            rudder_trim,

            flaps,

            pitch,
            rudder,

            trim_reset_rudder,

            nws_right,
            nws_left,
            tv,
        }
        internal enum WPT_MGR
        {
            import_f10_waypoints = 3001,
            sync_waypoint,
            sync_markpoint,
            sync_transient,
            master_av,
            sync_course_p,
            sync_heading_p,
            sync_course_cp,
            sync_heading_cp,
            show_debug,

        }
        internal enum MISCELLANEOUS
        {
            Both_Windows_Toggle = 4001,
            wipers,
            hide_yoke,
            cargo_door_bottom,
            cargo_skids,
            cargo_open_all,
            cargo_close_all,
            cargo_bay_view,
        }
        internal enum THROTTLE_PANEL
        {
            to_mode = 3001,
            beta_mode,
            flt_mode,
            hotel_mode,
            normalidle_mode,
            kbd_input,
            walk_forward_back,
            walk_left_right,
            walk_turn_left,
            walk_turn_right,
            player_input_response,
        }
        internal enum CURSOR
        {
            cursor_up_down = 3001,
            cursor_left_right,
            cursor_start_up,
            cursor_start_down,
            cursor_start_right,
            cursor_start_left,

            cursor_stop_up,
            cursor_stop_down,
            cursor_stop_right,
            cursor_stop_left,

            select,
            sync,
        }
        internal enum MECH_INTERFACE
        {
            flap_lever = 3001,
            flap_axis,
            cni_pri_toggle,

            lsgi_1,
            lsgi_2,
            lsgi_3,
            lsgi_4,
            pilot_window,
            copilot_window,

            cursor_reset,
            man_mode,
            gnd_mode,
            cptr_mode,
            cursor_hud,
            cursor_rng,
            cursor_zoom,

            cargo_door_toggle,

            pitch_trim_sync,
            roll_trim_sync,
            rudder_trim_sync,

            open_close_cabinet,
            airdrop_alarm_cover,
            airdrop_alarm,
            air_defelector,
            computer_drop,
            airdrop_caution,
            airdrop_jump,
            chute_release_cover,
            chute_release,

            cursor_hdd,
            ramp_ctrl,

            oil_flap_1_fixed,
            oil_flap_2_fixed,
            oil_flap_3_fixed,
            oil_flap_4_fixed,

            rudder_trim,
            parking_brake,

            elev_trim,

            cabin_door,
            trooper_door_right,
            trooper_door_left,
            close_all_doors,
            cargo_door_open,
            cargo_door_close,
            loading_ramp,
            ground_range,
            pilot_top_latch,
            pilot_bottom_latch,

            change_pod_mode,
            laser_on,
            loading_deck,
            laser_off,

            copilot_top_latch,
            copilot_bottom_latch,
        	Lock,
	        unlock,

            left_troop_door_close,
            right_troop_door_close,

            p_seat_arm_l,
            p_seat_arm_r,

            cp_seat_arm_l,
            cp_seat_arm_r,

            aug_seat_arm_l,
            aug_seat_arm_r,

            aug_seat_rotate,
            aug_seat_slide ,

            cursor_hdd_right,
            cursor_hdd_left,

            release_airdrop,

            quick_mode,
            cycle_mode,

            offset_aim_pt,
            oap_fwd,


            oil_flap_1_open,
            oil_flap_2_open,
            oil_flap_3_open,
            oil_flap_4_open,


            oil_flap_1_close,
            oil_flap_2_close,
            oil_flap_3_close,
            oil_flap_4_close,

            oil_flap_1_auto,
            oil_flap_2_auto,
            oil_flap_3_auto,
            oil_flap_4_auto,

            nose_release_gear_cover,
            nose_release_gear,

            trim_box_up,
            trim_box_dn,
            trim_box_left,
            trim_box_right,

            flap_lever_axis,
            hush,
            lsgi_all,

            flap_sync,

            tilt,
            loadmaster_ramp,

            crew_door_external,
            crew_door_internal,

            cargo_aux_pump_door,
            cargo_aux_pump_ramp,

            baro_offset,
            pitch_bar,
            pitch_bar_cage,

            toilet,
            elt_on_off,
    }
    internal enum GALLEY
        {
            power = 3001,
            coffee,

            ctr_shelf,
            ctr_shelf_stop_l,
            ctr_shelf_stop_r,

            btm_shelf,
            btm_shelf_stop_l,
            btm_shelf_stop_c,
            btm_shelf_stop_r,

            microwave_stopper,
            micro_door,
            micro_start,
            micro_clear,
            micro_0,
            micro_1,
            micro_2,
            micro_3,
            micro_4,
            micro_5,
            micro_6,
            micro_7,
            micro_8,
            micro_9,
            popcorn,
            min,

            flood_light,
            lqcdnt_1,
            lqcdnt_2,

            top_cab_stopper,
            top_cab_open,

            trash_door_stopper,
            trash_door_latch,
            trash_opening,

            bottom_cab_latch,
            bottom_cab_pull,

            shelf_stopper_1,
            shelf_stopper_2,
            shelf_stopper_3,
            shelf_stopper_4,

            bev_shield,

            p_pull_cable,
            p_pull_cable_stop,
            cp_pull_cable,
            cp_pull_cable_stop,

            p_pull_cable_low,
            p_pull_cable_low_stop,

            cp_pull_cable_low,
            cp_pull_cable_low_stop,

            move_fwd_back,
            move_left_right,
            move_jump,
            move_crouch,
            rotate_lr,
            rotate_ud,
            equip_sidearm,
            toggle_sidearm,
            unload_last_to_here,
            kill_loadmaster,

        }
        internal enum P_AMU
        {
            l_key_1 = 3001,
            l_key_2,
            l_key_3,
            l_key_4,
            l_key_5,
            l_key_6,
            l_key_7,
            l_key_8,
            amu_brightness,
            r_hdd_brightness,

            r_key_1,
            r_key_2,
            r_key_3,
            r_key_4,
            r_key_5,
            r_key_6,
            r_key_7,
            r_key_8,

            l_hdd_brightness,

            amu_brightness_down,
            r_hdd_brightness_down,
            l_hdd_brightness_down,
            hud_latch,

            brightness_knob,
            brightness_knob_auto,
            vis_disp_mode,
            nav_data_layer,
            tac_data_layer,
            FPM_cage,
            offside_switch,
            CAT2_sub_mode,
            blank1,
            blank2,
            force_down,

        }
        internal enum C_AMU
        {
            r_key_1 = 3001,
            r_key_2,
            r_key_3,
            r_key_4,
            r_key_5,
            r_key_6,
            r_key_7,
            r_key_8,

            amu_brightness,
            r_hdd_brightness,

            l_key_1,
            l_key_2,
            l_key_3,
            l_key_4,
            l_key_5,
            l_key_6,
            l_key_7,
            l_key_8,

            l_hdd_brightness,
            amu_brightness_down,
            r_hdd_brightness_down,
            l_hdd_brightness_down,
            hud_latch,

            brightness_knob,
            brightness_knob_auto,
            vis_disp_mode,
            nav_data_layer,
            tac_data_layer,
            FPM_cage,
            offside_switch,
            CAT2_sub_mode,
            blank1,
            blank2,
            force_down,
        }
        internal enum CMS
        {
            arm_toggle_cms = 3001,
            release_snar,
            cms_profile_mode,
            ircm_toggle,
            emerg_jett,
            emerg_jett_cover,
            mws_arm,
            man_prog,
            rwr_search,
            rwr_track,
            rwr_handoff,
            rwr_alt,
            rwr_sep,
        }
        internal enum HYD_SYSTEM
        {
            emerg_brake_sel = 3001,
            aux_pump,
            hyd_util_1,
            hyd_util_2,
            hyd_boost_1,
            hyd_boost_2,
            suction_boost_pump_util,
            suction_boost_pump_boost,
            emerg_hyd_pump,
            elevator_boost_guard,
            elevator_util_guard,
            rudder_boost_guard,
            rudder_util_guard,
            ale_boost_guard,
            ale_util_guard,
            elevator_boost,
            elevator_util,
            rudder_boost,
            rudder_util,
            ale_boost,
            ale_util,
            gear_lever,
            gear_up,
            gear_down,
            force_gear_up,
            force_gear_down,
            gear_lock_release,
            cargo_aux_pump_on,

        }
        internal enum ENGINE_ELEC_APU_CTRL
        {
            battery = 3001,
            gen_1,
            gen_2,
            gen_3,
            gen_4,
            ext_elec,

            engine_1_start_select,
            engine_2_start_select,
            engine_3_start_select,
            engine_4_start_select,
            engine_1_stop,
            engine_2_stop,
            engine_3_stop,
            engine_4_stop,
            apu_selector,
            wipers,
            engine_1_fire,
            engine_2_fire,
            engine_3_fire,
            engine_4_fire,
            apu_fire,
            engine_1_fire_pull,
            engine_2_fire_pull,
            engine_3_fire_pull,
            engine_4_fire_pull,
            apu_fire_pull,
            apu_alarm,
            emerg_xlt,
            anti_skid,
            apu_select_stop,
            apu_start_sync,
            wipers_stop,
            bat_test,
            wiper_sync,

            guard_1,
            guard_2,
            guard_3,
            guard_4,
            fadec_1,
            fadec_2,
            fadec_3,
            fadec_4,
            prop_ctrl_1,
            prop_ctrl_2,
            prop_ctrl_3,
            prop_ctrl_4,
            atcs_guard,
            prop_sync,
            atcs,

            bleed_apu,
            iso_left,
            divider,
            iso_right,
            bleed_eng_1,
            bleed_eng_2,
            bleed_eng_3,
            bleed_eng_4,
            ice_prop_1,
            ice_prop_2,
            ice_prop_3,
            ice_prop_4,
            ice_engine,
            ice_wing,
            de_ice,
            ice_pitot_c,
            ice_pitot_cp,
            ice_nesa_ctr,
            ice_nesa_side,
        }
        internal enum FUEL
        {
            transfer_main_1 = 3001,
            transfer_main_2,
            transfer_main_3,
            transfer_main_4,
            transfer_aux_1,
            transfer_aux_2,
            transfer_ext_1,
            transfer_ext_2,

            main_xfeed,
            test,
            xfeed_eng1,
            xfeed_eng2,
            xfeed_eng3,
            xfeed_eng4,
            tank_select,
            dump_guard_right,
            dump_guard_left,
            spr_valve,
            qty_set,
            qty_set_abs,
            dump_right,
            dump_left,
        }
        internal enum NAV_RADAR
        {
            master_mode = 3001,
            intensity_mode,
            intensity,
            gain,
            ofs,
            frz,
            pen,
            sctr,
            psel,
            prcn,
            map_mode,
            wx_mode,
            sp_mode,
            msn_mode,
            ws_mode,
            bcn_mode,
            master_off,
            master_on,
            master_test,

        }
        internal enum VOL_CTRL
        {
            master_vol = 3001,
            int_vol,
            h1_vol,
            h2_vol,
            pa_vol,
            pa_gain_vol,
            vox_sense_vol,
            v1_vol,
            v2_vol,
            sat_vol,
            pvt_vol,
            vox_hm_vol,
            u1_vol,
            u2_vol,
            int_radio_toggle,
            int_pull,
            h1_pull,
            h2_pull,
            pa_pull,
            v1_pull,
            v2_pull,
            sat_pull,
            pvt_pull,
            vox_hm_pull,
            u1_pull,
            u2_pull,
            mic_mode,
            trans_mode,

            cp_master_vol,
            int_vol_cp,
            h1_vol_cp,
            h2_vol_cp,
            pa_vol_cp,
            pa_gain_vol_cp,
            vox_sense_vol_cp,
            v1_vol_cp,
            v2_vol_cp,
            sat_vol_cp,
            pvt_vol_cp,
            vox_hm_vol_cp,
            u1_vol_cp,
            u2_vol_cp,
            int_radio_toggle_cp,
            int_pull_cp,
            h1_pull_cp,
            h2_pull_cp,
            pa_pull_cp,
            v1_pull_cp,
            v2_pull_cp,
            sat_pull_cp,
            pvt_pull_cp,
            vox_hm_pull_cp,
            u1_pull_cp,
            u2_pull_cp,
            mic_mode_cp,
            trans_mode_cp,

            vor1,
            vor2,
            tacan1,
            tacan2,
            adf1,
            adf2,
            sar,
            blank,
            bcn,
            rwr,
            vor1_pull,
            vor2_pull,
            tacan1_pull,
            tacan2_pull,
            adf1_pull,
            adf2_pull,
            sar_pull,
            blank_pull,
            bcn_pull,
            rwr_pull,

            vor1_cp,
            vor2_cp,
            tacan1_cp,
            tacan2_cp,
            adf1_cp,
            adf2_cp,
            sar_cp,
            blank_cp,
            bcn_cp,
            rwr_cp,
            vor1_pull_cp,
            vor2_pull_cp,
            tacan1_pull_cp,
            tacan2_pull_cp,
            adf1_pull_cp,
            adf2_pull_cp,
            sar_pull_cp,
            blank_pull_cp,
            bcn_pull_cp,
            rwr_pull_cp,

            aug_master_vol,
            vor1_aug,
            vor2_aug,
            tacan1_aug,
            tacan2_aug,
            adf1_aug,
            adf2_aug,
            sar_aug,
            blank_aug,
            bcn_aug,
            rwr_aug,
            vor1_pull_aug,
            vor2_pull_aug,
            tacan1_pull_aug,
            tacan2_pull_aug,
            adf1_pull_aug,
            adf2_pull_aug,
            sar_pull_aug,
            blank_pull_aug,
            bcn_pull_aug,
            rwr_pull_aug,

            int_vol_aug,
            h1_vol_aug,
            h2_vol_aug,
            pa_vol_aug,
            pa_gain_vol_aug,
            vox_sense_vol_aug,
            v1_vol_aug,
            v2_vol_aug,
            sat_vol_aug,
            pvt_vol_aug,
            vox_hm_vol_aug,
            u1_vol_aug,
            u2_vol_aug,
            int_radio_toggle_aug,
            int_pull_aug,
            h1_pull_aug,
            h2_pull_aug,
            pa_pull_aug,
            v1_pull_aug,
            v2_pull_aug,
            sat_pull_aug,
            pvt_pull_aug,
            vox_hm_pull_aug,
            u1_pull_aug,
            u2_pull_aug,
            mic_mode_aug,
            trans_mode_aug,

            arc_l1,
            arc_l2,
            arc_l3,
            arc_tod_snd,
            arc_tod_rcv,
            arc_gps,
            arc_rt_select,
            arc_menu,
            arc_xmt_rec_send,
            arc_am_fm,
            arc_rcu_offset,
            arc_brt_up,
            arc_brt_dn,
            arc_enter,
            arc_sql,
            arc_rcu_1,
            arc_rcu_2,
            arc_rcu_3,
            arc_rcu_4,
            arc_rcu_5,
            arc_op_mode,
            arc_channel,
            arc_q_mode,

            mic_stop,
            mic_stop_cp,
            mic_stop_aug,

            play_boot,
        }
        internal enum CARGO_HANDLER
        {
            show_hide_interface = 3001,
            add_unit,
            remove_unit,
            unit_at_cursor,
            load_unit_center,
            unload_unit,
            ramp_gui,
            lock_unit,
            unlock_unit,
            cds_connect,
            cds_disconnect,
            load_unit_right,
            load_unit_left,
            do_load_now,
            fail_norm_brakes,
            fail_emerg_brakes,
            stag_1,
            stag_2,
            stag_3,
            stag_4,
            hot_1,
            hot_2,
            hot_3,
            hot_4,
            flameout_1,
            flameout_2,
            flameout_3,
            flameout_4,
            no_lightoff_1,
            no_lightoff_2,
            no_lightoff_3,
            no_lightoff_4,
            oil_pump_1,
            oil_pump_2,
            oil_pump_3,
            oil_pump_4,
            oil_cooler_1,
            oil_cooler_2,
            oil_cooler_3,
            oil_cooler_4,

            unlock_all,
            stage_loadable,
            unstage_loadable,
            set_lat_position_null,
            set_lat_position_center,
            set_lat_position_left,
            set_lat_position_right,
            toggle_default_lat_pos,
            unstage_all,

            set_sta_position_c,
            set_sta_position_d,
            set_sta_position_e,
            set_sta_position_f,
            set_sta_position_g,
            set_sta_position_h,
            set_sta_position_i,
            set_sta_position_j,
            set_sta_position_null,
            show_hide_spawn,
            create_unit,
            select_spawn_opt,

            loadmaster_cover,

            set_parachute_delay,
            open_load_contents,
            close_load_contents,
            load_contents_missiles,
            load_contents_bombs,
            load_contents_other,

            checklists,
            mark_current_checklist_item,

            KBD_0,
            KBD_1,
            KBD_2,
            KBD_3,
            KBD_4,
            KBD_5,
            KBD_6,
            KBD_7,
            KBD_8,
            KBD_9,
            KBD_DOT,
            KBD_PLUS,
            KBD_MINUS,
            KBD_A,
            KBD_B,
            KBD_C,
            KBD_D,
            KBD_E,
            KBD_F,
            KBD_G,
            KBD_H,
            KBD_I,
            KBD_J,
            KBD_K,
            KBD_L,
            KBD_M,
            KBD_N,
            KBD_O,
            KBD_P,
            KBD_Q,
            KBD_R,
            KBD_S,
            KBD_T,
            KBD_U,
            KBD_V,
            KBD_W,
            KBD_X,
            KBD_Y,
            KBD_Z,
            KBD_EQUALS,
            KBD_LEFT_BRACKET,
            KBD_RIGHT_BRACKET,
            KBD_BACKTICK,
            KBD_FWD_SLASH,
            KBD_BACK_SLASH,
            KBD_APOSTROPHE,
            KBD_COMMA,
            KBD_SEMICOLON,
            KBD_BACKSPACE,
            KBD_SPACE,
            KBD_TAB,
            KBD_LEFT,
            KBD_RIGHT,
            KBD_UP,
            KBD_DOWN,
            KBD_DELETE,
            KBD_SHIFT,
            KBD_END,
            KBD_HOME,
            KBD_ENTER,
            KBD_INSERT,
            KBD_PG_DOWN,
            KBD_PG_UP,

            TABLET_CLICK,

            MOUSE_CLICK_LEFT,
            KEYBOARD_INPUT,
            MOUSE_X,
            MOUSE_Y,
            MOUSE_CLICK_RIGHT,
            MOUSE_CLICK_CENTER,
            MOUSE_SCROLL,
        }
        internal enum ARC_210
        {
            l1 = 3001,
            l2,
            l3,
            tod_snd,
            tod_rcv,
            gps,
            rt_select,
            menu,
            xmt_rec_send,
            am_fm,
            rcu_offset,
            brt_up,
            brt_dn,
            enter,
            sql,
            rcu_1,
            rcu_2,
            rcu_3,
            rcu_4,
            op_mode,
            rcu_5,
            channel,
            q_mode,
        }
        internal enum WEAPONS
        {
            slew_up_down = 3001,
            slew_left_right
        }


    }
}
