//  Copyright 2024 Helios Contributors
//    
//  Helios is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  Helios is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.

namespace GadrocsWorkshop.Helios.Interfaces.DCS.C130J
{
    internal enum devices
    {
        MAIN_COMPUTER = 1,
        ENGINE_APU_CTRL = 2,
        THROTTLE_SYNC = 3,
        SYNC_MACHINE = 4,
        ELECTRIC_SYSTEM = 5,
        VHF1 = 6,
        UHF1 = 7,
        VHF2 = 8,
        UHF2 = 9,
        HF1 = 10,
        HF2 = 11,
        TACAN1 = 12,
        TACAN2 = 13,
        VORILS1 = 14,
        VORILS2 = 15,
        ADF1 = 16,
        ADF2 = 17,
        WayPointMgr = 18,
        CNBP = 19,
        P_DISPLAYS = 20,
        C_DISPLAYS = 21,
        PFD = 22,
        TAWS_Device = 23,
        RWR = 24,
        P_CNI = 25,
        C_CNI = 26,
        AC_CNI = 27,
        INTERCOM = 28,
        AMU001 = 29,
        AMU002 = 30,
        AMU003 = 31,
        AMU004 = 32,
        PILOT_CPT_INTERFACE = 33,
        COPILOT_CPT_INTERFACE = 34,
        PILOT_HUD_PANEL = 35,
        COPILOT_HUD_PANEL = 36,
        PILOT_REF_MODE_PANEL = 37,
        COPILOT_REF_MODE_PANEL = 38,
        LIGHTING_PANELS = 39,
        ECM = 40,
        MWS = 41,
        CMS_DISPENSER = 42,
        CMS_MGR = 43,
        CURSOR = 44,
        IRCM = 45,
        MECH_INTERFACE = 46,
        J_WORLD = 47,
        CARGO_HANDLER = 48,
        STANDBY = 49,
        WEAPONS = 50,
        IFF = 51,
        AP_INTERFACE = 52,
        AP_MGR = 53,
        DLINK = 54,
        Autopilot = 55,
        HDD001 = 56,
        HDD002 = 57,
        HDD003 = 58,
        HDD004 = 59,
        SOUND_ENG = 60,
        HOTAS_P = 61,
        HOTAS_C = 62,
        INTERCOM_CP = 63,
        FUEL_SYSTEM = 64,
        FADEC = 65,
        APU = 66,
        NAV_RADAR = 67,
        ACAWS = 68,
        VOLUME_MANAGER = 69,
        PLANE_ATM = 70,
        BLEED_AIR = 71,
        HYDRAULICS = 72,
        CDMU = 73,
        SOUNDER = 74,
        SP_RAD = 75,
        TIMER = 76,
        GPS1 = 77,
        GPS2 = 78,
        RADALT_1 = 79,
        RADALT_2 = 80,
        GALLEY = 81,
        OXYGEN = 82,
        PHYSIO = 83,
        INS1 = 84,
        INS2 = 85,
        INS_MGR = 86,
        NVG = 87,
        MECH_GYRO = 88,
        MACROS = 89,
        HEAD = 90,
        STB_COMPASS = 91,
        ARC_210 = 92,
        CAPS = 93,
        AUX_SYNC = 94,
        KNEEBOARD = 95,
        ROUTE_SYNC = 96,
        FAILURE_MGR = 97,
    }
}
