//  Copyright 2024 Helios Contributors
//    
//  Helios is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  Helios is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.

namespace GadrocsWorkshop.Helios.Interfaces.DCS.C130J
{
    internal enum devices
    {
        MAIN_COMPUTER,
        ENGINE_APU_CTRL,
        THROTTLE_SYNC,
        SYNC_MACHINE,
        ELECTRIC_SYSTEM,
        VHF1,
        UHF1,
        VHF2,
        UHF2,
        HF1,
        HF2,
        TACAN1,
        TACAN2,
        VORILS1,
        VORILS2,
        ADF1,
        ADF2,
        WayPointMgr,
        CNBP,
        P_DISPLAYS,
        C_DISPLAYS,
        PFD,
        TAWS_Device,
        RWR,
        P_CNI,
        C_CNI,
        AC_CNI,
        INTERCOM,
        AMU001,
        AMU002,
        AMU003,
        AMU004,
        PILOT_CPT_INTERFACE,
        COPILOT_CPT_INTERFACE,
        PILOT_HUD_PANEL,
        COPILOT_HUD_PANEL,
        PILOT_REF_MODE_PANEL,
        COPILOT_REF_MODE_PANEL,
        LIGHTING_PANELS,
        ECM,
        MWS,
        CMS_DISPENSER,
        CMS_MGR,
        CURSOR,
        IRCM,
        MECH_INTERFACE,
        J_WORLD,
        CARGO_HANDLER,
        STANDBY,
        WEAPONS,
        IFF,
        AP_INTERFACE,
        AP_MGR,
        DLINK,
        Autopilot,
        HDD001,
        HDD002,
        HDD003,
        HDD004,
        SOUND_ENG,
        HOTAS_P,
        HOTAS_C,
        INTERCOM_CP,
        FUEL_SYSTEM,
        FADEC,
        APU,
        NAV_RADAR,
        ACAWS,
        VOLUME_MANAGER,
        PLANE_ATM,
        BLEED_AIR,
        HYDRAULICS,
        CDMU,
        SOUNDER,
        SP_RAD,
        TIMER,
        GPS1,
        GPS2,
        RADALT_1,
        RADALT_2,
        GALLEY,
        OXYGEN,
        PHYSIO,
        INS1,
        INS2,
        INS_MGR,
        NVG,
        MECH_GYRO,
        MACROS,
        HEAD,
        STB_COMPASS,
        ARC_210,
        CAPS,
        AUX_SYNC,
        KNEEBOARD,
        ROUTE_SYNC,
        FAILURE_MGR
    }
}
