//  Copyright 2020 Ammo Goettsch
//  Copyright 2024 Helios Contributors
//    
//  Helios is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  Helios is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.

namespace GadrocsWorkshop.Helios.Interfaces.DCS.Mosquito
{
    using GadrocsWorkshop.Helios.ComponentModel;
    using GadrocsWorkshop.Helios.Interfaces.DCS.Common;
    //using GadrocsWorkshop.Helios.Interfaces.DCS.Mosquito.Functions;
    using System.Windows;


    [HeliosInterface(
        "Helios.Mosquito",                         // Helios internal type ID used in Profile XML, must never change
        "DCS Mosquito FB Mk VI",                   // human readable UI name for this interface
        typeof(DCSInterfaceEditor),            // uses basic DCS interface dialog
        typeof(UniqueHeliosInterfaceFactory),   // can't be instantiated when specific other interfaces are present
        UniquenessKey = "Helios.DCSInterface")]   // all other DCS interfaces exclude this interface

    public class MosquitoInterface : DCSInterface
    {

        public MosquitoInterface(string name)
            : base(name, "MosquitoFBMkVI", "pack://application:,,,/Mosquito;component/Interfaces/ExportFunctions.lua")
        {

            // not setting Vehicles at all results in the module name identifying the only 
            // supported aircraft
            // XXX not yet supported
            // Vehicles = new string[] { ModuleName, "other aircraft", "another aircraft" };

            // see if we can restore from JSON
#if (!DEBUG)
                        if (LoadFunctionsFromJson())
                        {
                            return;
                        }
#endif

            //ProcessDCSBios processDCSBios = new ProcessDCSBios(); // remove after Mossie interface built
            AddFunction(new PushButton(this, "5", "3005", "245", "Stick", "Stick Button A - Gun Trigger", "%1d"));   // "STICK_BTN_A"
            AddFunction(new PushButton(this, "5", "3006", "246", "Stick", "Stick Button B1 - Cannon Trigger", "%1d"));   // "STICK_BTN_B1"
            AddFunction(new Axis(this, "2", "3001", "248", 0.1d, 0d, 1d, "Stick", "Stick Wheel Brakes Lever", false, "%.1f"));   // "STICK_WH_BRK"
            AddFunction(new PushButton(this, "2", "3004", "291", "Stick", "Stick Wheel Brakes Lever Lock", "%1d"));   // "STICK_WH_BRK_LOCK"
            AddFunction(Switch.CreateToggleSwitch(this, "2", "3022", "251", "1", "Position 1", "0", "Position 2", "Cockpit", "Left Side Window Open/Close Control", "%1d"));   // "WINDOW_CONTROL_L"
            AddFunction(Switch.CreateToggleSwitch(this, "2", "3063", "253", "1", "Position 1", "0", "Position 2", "Cockpit", "Right Side Window Open/Close Control", "%1d"));   // "WINDOW_CONTROL_R"
            AddFunction(new PushButton(this, "2", "3071", "312", "Cockpit", "Armor Headrest Lock", "%1d"));   // "ARMOR_HEADREST"
            AddFunction(new Axis(this, "5", "3045", "107", 0.1d, 0d, 1d, "Reflector Sight", "Reflector Sight Setter Rings Range", false, "%.1f"));   // "GUNSIGHT_RANGE"
            AddFunction(new Axis(this, "5", "3048", "108", 0.1d, 0d, 1d, "Reflector Sight", "Reflector Sight Setter Rings Span", false, "%.1f"));   // "GUNSIGHT_SPAN"
            AddFunction(new Axis(this, "4", "3009", "13", 0.1d, 0d, 1d, "Reflector Sight", "Reflector Sight Dimmer", false, "%.1f"));   // "GUNSIGHT_L_DIM"
            AddFunction(Switch.CreateToggleSwitch(this, "3", "3009", "124", "1", "Position 1", "0", "Position 2", "JBA", "Master Gate Switch", "%1d"));   // "MASTER_SWITCH"
            AddFunction(Switch.CreateToggleSwitch(this, "3", "3001", "125", "1", "Position 1", "0", "Position 2", "JBA", "Magneto Switch Port 1", "%1d"));   // "PORT_MAGNETO_1"
            AddFunction(Switch.CreateToggleSwitch(this, "3", "3003", "126", "1", "Position 1", "0", "Position 2", "JBA", "Magneto Switch Port 2", "%1d"));   // "PORT_MAGNETO_2"
            AddFunction(Switch.CreateToggleSwitch(this, "3", "3052", "129", "1", "Position 1", "0", "Position 2", "JBA", "Starter Switch Cover Port", "%1d"));   // "PORT_START_CVR"
            AddFunction(new PushButton(this, "3", "3054", "131", "JBA", "Starter Switch Port", "%1d"));   // "PORT_START_SW"
            AddFunction(Switch.CreateToggleSwitch(this, "3", "3058", "133", "1", "Position 1", "0", "Position 2", "JBA", "Booster Switch Cover Port", "%1d"));   // "PORT_BOOST_CVR"
            AddFunction(new PushButton(this, "3", "3060", "135", "JBA", "Booster Switch Port", "%1d"));   // "PORT_BOOST_SW"
            AddFunction(Switch.CreateToggleSwitch(this, "3", "3081", "354", "1", "Position 1", "0", "Position 2", "JBA", "Feathering Switch Port", "%1d"));   // "PORT_AIRSCREW"
            AddFunction(Switch.CreateToggleSwitch(this, "4", "3062", "112", "1", "Position 1", "0", "Position 2", "JBA", "Radiator Flap Switch Port", "%1d"));   // "PORT_RAD_FLAP"
            AddFunction(Switch.CreateToggleSwitch(this, "4", "3064", "113", "1", "Position 1", "0", "Position 2", "JBA", "Radiator Flap Switch Starboard", "%1d"));   // "STBD_RAD_FLAP"
            AddFunction(Switch.CreateToggleSwitch(this, "3", "3082", "355", "1", "Position 1", "0", "Position 2", "JBA", "Feathering Switch Starboard", "%1d"));   // "STBD_AIRSCREW"
            AddFunction(Switch.CreateToggleSwitch(this, "3", "3061", "134", "1", "Position 1", "0", "Position 2", "JBA", "Booster Switch Cover Starboard", "%1d"));   // "STBD_BOOST_CVR"
            AddFunction(new PushButton(this, "3", "3063", "136", "JBA", "Booster Switch Starboard", "%1d"));   // "STBD_BOOST_SW"
            AddFunction(Switch.CreateToggleSwitch(this, "3", "3055", "130", "1", "Position 1", "0", "Position 2", "JBA", "Starter Switch Cover Starboard", "%1d"));   // "STBD_START_CVR"
            AddFunction(new PushButton(this, "3", "3057", "132", "JBA", "Starter Switch Starboard", "%1d"));   // "STBD_START_SW"
            AddFunction(Switch.CreateToggleSwitch(this, "3", "3005", "127", "1", "Position 1", "0", "Position 2", "JBA", "Magneto Switch Starboard 1", "%1d"));   // "STBD_MAGNETO_1"
            AddFunction(Switch.CreateToggleSwitch(this, "3", "3007", "128", "1", "Position 1", "0", "Position 2", "JBA", "Magneto Switch Starboard 2", "%1d"));   // "STBD_MAGNETO_2"
            AddFunction(new Axis(this, "4", "3053", "14", 0.1d, 0d, 1d, "JBA", "Right Flood Light Dimmer", false, "%.1f"));   // "FLOOD_L_DIM_R"
            AddFunction(new Axis(this, "4", "3056", "15", 0.1d, 0d, 1d, "JBA", "J.B.B. Flood Light Dimmer", false, "%.1f"));   // "BOX_B_L_DIM"
            AddFunction(Switch.CreateToggleSwitch(this, "4", "3066", "114", "1", "Position 1", "0", "Position 2", "JBA", "Tropical Air Filter Switch", "%1d"));   // "AIR_FILTER"
            AddFunction(Switch.CreateToggleSwitch(this, "2", "3065", "282", "1", "Position 1", "0", "Position 2", "JBA", "Fuel Pump Light Cover", "%1d"));   // "FUEL_PUMP_L_CVR"
            AddFunction(new FlagValue(this, "281", "JBA Lights", "Fuel Pump Light (yellow)", "True when indicator is lit", "%1d"));   // "FUEL_PUMP_L"
            AddFunction(new RotaryEncoder(this, "8", "3001", "49", 0.01d, "Main Panel", "Repeater Compass Course Set"));   // "REP_COMP"
            AddFunction(new RotaryEncoder(this, "2", "3010", "72", 0.01d, "Main Panel", "Altimeter Set"));   // "ALT_SET"
            AddFunction(new RotaryEncoder(this, "2", "3013", "74", 0.01d, "Main Panel", "Directional Gyro Set"));   // "DI_SET"
            AddFunction(new RotaryEncoder(this, "2", "3018", "304", 0.01d, "Main Panel", "U/C Indicator Blind Up/Down"));   // "UC_BLIND"
            AddFunction(Switch.CreateToggleSwitch(this, "15", "3003", "84", "1", "Position 1", "0", "Position 2", "Main Panel", "Oxygen Regulator Port", "%1d"));   // "PORT_OXY_VALVE"
            AddFunction(new PushButton(this, "3", "3049", "292", "Main Panel", "Boost Cut-Off T-Handle", "%1d"));   // "BOOST_CUT_OFF"
            AddFunction(Switch.CreateToggleSwitch(this, "4", "3018", "62", "1", "Position 1", "0", "Position 2", "Main Panel", "Landing Light Switch Port", "%1d"));   // "PORT_LAND_L_SW"
            AddFunction(Switch.CreateToggleSwitch(this, "4", "3020", "63", "1", "Position 1", "0", "Position 2", "Main Panel", "Landing Light Switch Starboard", "%1d"));   // "STBD_LAND_L_SW"
            AddFunction(Switch.CreateThreeWaySwitch(this, "17", "115", "3001", "1", "Position 1", "0", "Position 2", "-1", "Position 3", "Main Panel", "Bomb Doors Lever", "%1d"));   // "BOMB_DOORS_LVR"
            AddFunction(Switch.CreateThreeWaySwitch(this, "17", "116", "3002", "1", "Position 1", "0", "Position 2", "-1", "Position 3", "Main Panel", "Chassis Lever", "%1d"));   // "CHASSIS_LVR"
            AddFunction(Switch.CreateThreeWaySwitch(this, "17", "118", "3003", "1", "Position 1", "0", "Position 2", "-1", "Position 3", "Main Panel", "Flaps Lever", "%1d"));   // "FLAPS_LVR"
            AddFunction(Switch.CreateToggleSwitch(this, "17", "3004", "117", "1", "Position 1", "0", "Position 2", "Main Panel", "Chassis Lever Gate", "%1d"));   // "CHASSIS_GATE"
            AddFunction(Switch.CreateToggleSwitch(this, "17", "3006", "119", "1", "Position 1", "0", "Position 2", "Main Panel", "Flaps Lever Gate", "%1d"));   // "FLAPS_GATE"
            AddFunction(Switch.CreateToggleSwitch(this, "5", "3001", "120", "1", "Position 1", "0", "Position 2", "Main Panel", "Gun Firing Master Switch Cover", "%1d"));   // "GUN_MASTER_CVR"
            AddFunction(new Switch(this, "5", "121", SwitchPositions.Create(2, -1, 2, "3003", "Position ", "%.2f"), "Main Panel", "Gun Firing Master Switch", "%.2f"));   // "GUN_MASTER"
            AddFunction(Switch.CreateToggleSwitch(this, "23", "3001", "370", "1", "Position 1", "0", "Position 2", "Main Panel", "De-Ice Glycol Pump Handle", "%1d"));   // "DE_ICE_PUMP"
            AddFunction(new RotaryEncoder(this, "2", "3053", "111", 0.01d, "Main Panel", "Rudder Trim"));   // "RUDDER_TRIM"
            AddFunction(new RotaryEncoder(this, "2", "3051", "280", 0.01d, "Main Panel", "Aileron Trim"));   // "AILERON_TRIM"
            AddFunction(new Axis(this, "4", "3059", "16", 0.1d, 0d, 1d, "Main Panel", "Bomb Panel Flood Dimmer", false, "%.1f"));   // "BOMB_PANEL_L_DIM"
            AddFunction(Switch.CreateToggleSwitch(this, "2", "3067", "284", "1", "Position 1", "0", "Position 2", "Main Panel", "Bomb Door Light Cover", "%1d"));   // "BOMB_DOOR_L_CVR"
            AddFunction(Switch.CreateToggleSwitch(this, "5", "3056", "144", "1", "Position 1", "0", "Position 2", "Main Panel", "Container Jettison Cover", "%1d"));   // "JETT_CONT_CVR"
            AddFunction(new PushButton(this, "5", "3058", "145", "Main Panel", "Container Jettison Button", "%1d"));   // "JETT_CONT"
            AddFunction(Switch.CreateToggleSwitch(this, "5", "3059", "311", "1", "Position 1", "0", "Position 2", "Main Panel", "Bomb Panel Cover", "%1d"));   // "BOMB_PANEL_CVR"
            AddFunction(Switch.CreateToggleSwitch(this, "5", "3061", "143", "1", "Position 1", "0", "Position 2", "Main Panel", "Cine Camera Changeover Switch", "%1d"));   // "CINE_CAM"
            AddFunction(Switch.CreateToggleSwitch(this, "5", "3063", "148", "1", "Position 1", "0", "Position 2", "Main Panel", "Wing Ordnance 1 Switch", "%1d"));   // "WING_ORD_1"
            AddFunction(Switch.CreateToggleSwitch(this, "5", "3065", "149", "1", "Position 1", "0", "Position 2", "Main Panel", "Wing Ordnance 2 Switch", "%1d"));   // "WING_ORD_2"
            AddFunction(Switch.CreateToggleSwitch(this, "5", "3067", "150", "1", "Position 1", "0", "Position 2", "Main Panel", "Fuselage Bombs 3 Switch", "%1d"));   // "FUSELAGE_BOMB_3"
            AddFunction(Switch.CreateToggleSwitch(this, "5", "3069", "151", "1", "Position 1", "0", "Position 2", "Main Panel", "Fuselage Bombs 4 Switch", "%1d"));   // "FUSELAGE_BOMB_4"
            AddFunction(Switch.CreateToggleSwitch(this, "5", "3071", "152", "1", "Position 1", "0", "Position 2", "Main Panel", "All Nose Bombs Switch", "%1d"));   // "NOSE_BOMBS"
            AddFunction(Switch.CreateToggleSwitch(this, "5", "3073", "153", "1", "Position 1", "0", "Position 2", "Main Panel", "All Tail Bombs Switch", "%1d"));   // "TAIL_BOMBS"
            AddFunction(new RotaryEncoder(this, "18", "3003", "90", 0.01d, "Main Panel", "Footage Indicator Scale"));   // "FOOTAGE_SCALE"
            AddFunction(Switch.CreateToggleSwitch(this, "18", "3001", "91", "1", "Position 1", "0", "Position 2", "Main Panel", "Footage Indicator Exposure Switch", "%1d"));   // "FOOTAGE_EXPOSURE"
            AddFunction(new NetworkValue(this, "47", "Main Panel Gauges", "Repeater Compass Heading", "", "Numeric Value between 0 and 1", BindingValueUnits.Numeric));   // "REP_COMP_HDG_G"
            AddFunction(new NetworkValue(this, "48", "Main Panel Gauges", "Repeater Compass Set Course", "", "Numeric Value between 0 and 1", BindingValueUnits.Numeric));   // "REP_COMP_CRS_G"
            AddFunction(new NetworkValue(this, "68", "Main Panel Gauges", "Altimeter 100", "", "Numeric Value between 0 and 1", BindingValueUnits.Numeric));   // "ALT_METER_100_G"
            AddFunction(new NetworkValue(this, "69", "Main Panel Gauges", "Altimeter 1000", "", "Numeric Value between 0 and 1", BindingValueUnits.Numeric));   // "ALT_METER_1000_G"
            AddFunction(new NetworkValue(this, "70", "Main Panel Gauges", "Altimeter 10000", "", "Numeric Value between 0 and 1", BindingValueUnits.Numeric));   // "ALT_METER_10000_G"
            AddFunction(new NetworkValue(this, "71", "Main Panel Gauges", "Altimeter Set Pressure", "", "Numeric Value between 0 and 1", BindingValueUnits.Numeric));   // "ALT_METER_SET_PRESS_G"
            AddFunction(new NetworkValue(this, "67", "Main Panel Gauges", "Variometer Gauge", "", "Numeric Value between -1 and 1", BindingValueUnits.Numeric));   // "VARIOMETER_100_G"
            AddFunction(new NetworkValue(this, "64", "Main Panel Gauges", "Airspeed Gauge", "", "Numeric Value between 0.0 and 0.5", BindingValueUnits.Numeric));   // "AIRSPEED_G"
            AddFunction(new NetworkValue(this, "65", "Main Panel Gauges", "AHorizon Bank", "", "Numeric Value between -1 and 1", BindingValueUnits.Numeric));   // "AHORIZON_BANK_G"
            AddFunction(new NetworkValue(this, "66", "Main Panel Gauges", "AHorizon Pitch", "", "Numeric Value between -1 and 1", BindingValueUnits.Numeric));   // "AHORIZON_PITCH_G"
            AddFunction(new NetworkValue(this, "73", "Main Panel Gauges", "DI Gauge", "", "Numeric Value between 0 and 1", BindingValueUnits.Numeric));   // "DI_G"
            AddFunction(new NetworkValue(this, "75", "Main Panel Gauges", "Sideslip Gauge", "", "Numeric Value between -1 and 1", BindingValueUnits.Numeric));   // "SIDESLIP_G"
            AddFunction(new NetworkValue(this, "76", "Main Panel Gauges", "Turn Gauge", "", "Numeric Value between -1 and 1", BindingValueUnits.Numeric));   // "TURN_G"
            AddFunction(new NetworkValue(this, "50", "Main Panel Gauges", "Tacho 1000 Port", "", "Numeric Value between 0 and 1", BindingValueUnits.RPM(5000)));   // "PORT_TACHO_1000_G"
            AddFunction(new NetworkValue(this, "51", "Main Panel Gauges", "Tacho 100 Port", "", "Numeric Value between 0 and 1", BindingValueUnits.Numeric));   // "PORT_TACHO_100_G"
            AddFunction(new NetworkValue(this, "52", "Main Panel Gauges", "Tacho 1000 Starboard", "", "Numeric Value between 0 and 1", BindingValueUnits.RPM(5000)));   // "STBD_TACHO_1000_G"
            AddFunction(new NetworkValue(this, "53", "Main Panel Gauges", "Tacho 100 Starboard", "", "Numeric Value between 0 and 1", BindingValueUnits.Numeric));   // "STBD_TACHO_100_G"
            AddFunction(new NetworkValue(this, "54", "Main Panel Gauges", "Boost Gauge Port", "", "Numeric Value between 0 and 1", BindingValueUnits.PoundsPerSquareInch));   // "PORT_BOOST_G"
            AddFunction(new NetworkValue(this, "55", "Main Panel Gauges", "Boost Gauge Starboard", "", "Numeric Value between 0 and 1", BindingValueUnits.PoundsPerSquareInch));   // "STBD_BOOST_G"
            AddFunction(new NetworkValue(this, "56", "Main Panel Gauges", "Oil Temperature Gauge Port", "", "Numeric Value between -1 and 1", BindingValueUnits.Numeric));   // "PORT_OIL_TEMP_G"
            AddFunction(new NetworkValue(this, "57", "Main Panel Gauges", "Oil Temperature Gauge Starboard", "", "Numeric Value between -1 and 1", BindingValueUnits.Numeric));   // "STBD_OIL_TEMP_G"
            AddFunction(new NetworkValue(this, "58", "Main Panel Gauges", "Oil Pressure Gauge Port", "", "Numeric Value between 0 and 1", BindingValueUnits.Numeric));   // "PORT_OIL_PRESS_G"
            AddFunction(new NetworkValue(this, "59", "Main Panel Gauges", "Oil Pressure Gauge Starboard", "", "Numeric Value between 0 and 1", BindingValueUnits.Numeric));   // "STBD_OIL_PRESS_G"
            AddFunction(new NetworkValue(this, "60", "Main Panel Gauges", "Radiator Temperature Gauge Port", "", "Numeric Value between -1 and 1", BindingValueUnits.Numeric));   // "PORT_RAD_TEMP_G"
            AddFunction(new NetworkValue(this, "61", "Main Panel Gauges", "Radiator Temperature Gauge Starboard", "", "Numeric Value between -1 and 1", BindingValueUnits.Numeric));   // "STBD_RAD_TEMP_G"
            AddFunction(new NetworkValue(this, "92", "Main Panel Gauges", "Inner Fuel Gauge Port", "", "Numeric Value between -1 and 1", BindingValueUnits.Numeric));   // "PORT_FUEL_IN_G"
            AddFunction(new NetworkValue(this, "93", "Main Panel Gauges", "Inner Fuel Gauge Starboard", "", "Numeric Value between -1 and 1", BindingValueUnits.Numeric));   // "STBD_FUEL_IN_G"
            AddFunction(new NetworkValue(this, "96", "Main Panel Gauges", "Outer Fuel Gauge Port", "", "Numeric Value between -1 and 1", BindingValueUnits.Numeric));   // "PORT_FUEL_OUT_G"
            AddFunction(new NetworkValue(this, "97", "Main Panel Gauges", "Outer Fuel Gauge Starboard", "", "Numeric Value between -1 and 1", BindingValueUnits.Numeric));   // "STBD_FUEL_OUT_G"
            AddFunction(new NetworkValue(this, "94", "Main Panel Gauges", "Fuel Gauge Central", "", "Numeric Value between -1 and 1", BindingValueUnits.Numeric));   // "CENTR_FUEL_G"
            AddFunction(new NetworkValue(this, "95", "Main Panel Gauges", "Fuel Gauge Long Range", "", "Numeric Value between -1 and 1", BindingValueUnits.Numeric));   // "LONG_FUEL_G"
            AddFunction(new NetworkValue(this, "82", "Main Panel Gauges", "Oxygen Delivery Gauge Port", "", "Numeric Value between 0 and 1", BindingValueUnits.Numeric));   // "PORT_OXY_DEV_G"
            AddFunction(new NetworkValue(this, "83", "Main Panel Gauges", "Oxygen Supply Gauge Port", "", "Numeric Value between 0 and 1", BindingValueUnits.Numeric));   // "PORT_OXY_SUPPLY_G"
            AddFunction(new NetworkValue(this, "155", "Main Panel Gauges", "Oxygen Delivery Gauge Starboard", "", "Numeric Value between 0 and 1", BindingValueUnits.Numeric));   // "STBD_OXY_DEV_G"
            AddFunction(new NetworkValue(this, "156", "Main Panel Gauges", "Oxygen Supply Gauge Starboard", "", "Numeric Value between 0 and 1", BindingValueUnits.Numeric));   // "STBD_OXY_SUPPLY_G"
            AddFunction(new NetworkValue(this, "81", "Main Panel Gauges", "Flaps Gauge", "", "Numeric Value between 0.0 and 0.7", BindingValueUnits.Numeric));   // "FLAPS_G"
            AddFunction(new NetworkValue(this, "85", "Main Panel Gauges", "Pneumatic Pressure Gauge", "", "Numeric Value between 0 and 1", BindingValueUnits.Numeric));   // "PNEU_PRESS_G"
            AddFunction(new NetworkValue(this, "86", "Main Panel Gauges", "Left Wheel Brake Gauge", "", "Numeric Value between 0 and 1", BindingValueUnits.Numeric));   // "WHEEL_BRK_L_G"
            AddFunction(new NetworkValue(this, "87", "Main Panel Gauges", "Right Wheel Brake Gauge", "", "Numeric Value between 0 and 1", BindingValueUnits.Numeric));   // "WHEEL_BRK_R_G"
            AddFunction(new NetworkValue(this, "314", "Main Panel Gauges", "Air Temperature Gauge", "", "Numeric Value between -1 and 1", BindingValueUnits.Numeric));   // "AIR_TEMP_G"
            AddFunction(new NetworkValue(this, "103", "Main Panel Gauges", "Voltmeter Gauge", "", "Numeric Value between 0 and 1", BindingValueUnits.Numeric));   // "VOLTMETER_G"
            AddFunction(new FlagValue(this, "283", "Main Panel Lights", "Bomb Door Light (yellow)", "True when indicator is lit", "%1d"));   // "BOMB_DOOR_L"
            AddFunction(new FlagValue(this, "271", "Main Panel Lights", "Main Panel Center Lamp (white)", "True when indicator is lit", "%1d"));   // "MAIN_PANEL_C_LAMP_L"
            AddFunction(new FlagValue(this, "270", "Main Panel Lights", "Main Panel Left Lamp (white)", "True when indicator is lit", "%1d"));   // "MAIN_PANEL_L_LAMP_L"
            AddFunction(new PushButton(this, "19", "3003", "101", "Clock", "Clock Set (Pull)", "%1d"));   // "CLOCK_PIN_PULL"
            AddFunction(new RotaryEncoder(this, "19", "3001", "102", 0.01d, "Clock", "Clock Set (Turn)"));   // "CLOCK_PIN_TURN"
            AddFunction(new RotaryEncoder(this, "19", "3005", "375", 0.01d, "Clock", "Clock Reference Hours"));   // "CLOCK_REF_H"
            AddFunction(new RotaryEncoder(this, "19", "3007", "376", 0.01d, "Clock", "Clock Reference Minutes"));   // "CLOCK_REF_M"
            AddFunction(new NetworkValue(this, "98", "Clock Gauges", "Clock Hours Gauge", "", "Numeric Value between -1 and 1", BindingValueUnits.Numeric));   // "CLOCK_H_G"
            AddFunction(new NetworkValue(this, "99", "Clock Gauges", "Clock Minutes Gauge", "", "Numeric Value between -1 and 1", BindingValueUnits.Numeric));   // "CLOCK_M_G"
            AddFunction(new NetworkValue(this, "100", "Clock Gauges", "Clock Seconds Gauge", "", "Numeric Value between -1 and 1", BindingValueUnits.Numeric));   // "CLOCK_S_G"
            AddFunction(new RotaryEncoder(this, "2", "3007", "28", 0.01d, "Port Wall", "Magnetic Compass"));   // "COMPASS_RING"
            AddFunction(new Axis(this, "4", "3006", "10", 0.1d, 0d, 1d, "Port Wall", "Emergency Light Rheostat", false, "%.1f"));   // "EMERG_L_DIM"
            AddFunction(new Axis(this, "4", "3012", "11", 0.1d, 0d, 1d, "Port Wall", "Compass Flood Light Dimmer", false, "%.1f"));   // "COMPASS_L_DIM"
            AddFunction(new Axis(this, "4", "3015", "12", 0.1d, 0d, 1d, "Port Wall", "L.H. Flood Light Dimmer", false, "%.1f"));   // "L_SIDE_L_DIM"
            AddFunction(Switch.CreateToggleSwitch(this, "5", "3008", "8", "1", "Position 1", "0", "Position 2", "Port Wall", "Wing Tank Jettison Cover", "%1d"));   // "JETT_W_TANK_CVR"
            AddFunction(new PushButton(this, "5", "3010", "9", "Port Wall", "Wing Tank Jettison Button", "%1d"));   // "JETT_W_TANK"
            AddFunction(new PushButton(this, "4", "3024", "294", "Port Wall", "UV Exciter Button", "%1d"));   // "UV_EXCITER"
            AddFunction(new Axis(this, "20", "3001", "295", 0.1d, 0d, 1d, "Port Wall", "LH UV Lamp Cap", false, "%.1f"));   // "LH_UV_CAP"
            AddFunction(new Axis(this, "21", "3001", "296", 0.1d, 0d, 1d, "Port Wall", "RH UV Lamp Cap", false, "%.1f"));   // "RH_UV_CAP"
            AddFunction(new Axis(this, "30", "3003", "7", 0.1d, 0d, 1d, "Port Wall", "Beam Approach Volume Rheostat", false, "%.1f"));   // "BA_VOLUME"
            AddFunction(Switch.CreateToggleSwitch(this, "4", "3001", "1", "1", "Position 1", "0", "Position 2", "Port Wall", "R.I. Compass Switch", "%1d"));   // "REP_COMPASS_SW1"
            AddFunction(Switch.CreateToggleSwitch(this, "4", "3002", "2", "1", "Position 1", "0", "Position 2", "Port Wall", "R.I. Compass De-ground Switch", "%1d"));   // "REP_COMPASS_SW2"
            AddFunction(Switch.CreateToggleSwitch(this, "4", "3004", "3", "1", "Position 1", "0", "Position 2", "Port Wall", "Beam Approach Switch", "%1d"));   // "BEAM_SW"
            AddFunction(Switch.CreateToggleSwitch(this, "24", "3099", "4", "1", "Position 1", "0", "Position 2", "Port Wall", "SCR-522 PTT Button", "%1d"));   // "SCR_PTT"
            AddFunction(new RotaryEncoder(this, "2", "3016", "279", 0.01d, "Port Wall", "Elevator Trim"));   // "ELEVATOR_TRIM"
            AddFunction(new FlagValue(this, "325", "Port Wall Lights", "Left UV Light (multi)", "True when indicator is lit", "%1d"));   // "UV_L_L"
            AddFunction(new FlagValue(this, "326", "Port Wall Lights", "Right UV Light (multi)", "True when indicator is lit", "%1d"));   // "UV_R_L"
            AddFunction(new PushButton(this, "24", "3001", "32", "Radio", "Radio OFF Button", "%1d"));   // "RADIO_OFF"
            AddFunction(new PushButton(this, "24", "3002", "33", "Radio", "Radio A Button", "%1d"));   // "RADIO_A"
            AddFunction(new PushButton(this, "24", "3003", "34", "Radio", "Radio B Button", "%1d"));   // "RADIO_B"
            AddFunction(new PushButton(this, "24", "3004", "35", "Radio", "Radio C Button", "%1d"));   // "RADIO_C"
            AddFunction(new PushButton(this, "24", "3005", "36", "Radio", "Radio D Button", "%1d"));   // "RADIO_D"
            AddFunction(Switch.CreateToggleSwitch(this, "24", "3006", "42", "1", "Position 1", "0", "Position 2", "Radio", "Radio Dimmer Toggle", "%1d"));   // "RADIO_L_DIM"
            AddFunction(Switch.CreateToggleSwitch(this, "24", "3017", "43", "1", "Position 1", "0", "Position 2", "Radio", "Radio Transmit Lock Toggle", "%1d"));   // "RADIO_TLOCK"
            AddFunction(new Switch(this, "24", "44", new SwitchPosition[] { new SwitchPosition("1.0", "Position 1", "3008"), new SwitchPosition("0.0", "Position 2", "3008"), new SwitchPosition("-1.0", "Position 3", "3007") }, "Radio", "Radio Mode Switch", "%.1f"));   // "RADIO_T_MODE"
            AddFunction(new Axis(this, "24", "3015", "364", 0.1d, 0d, 1d, "Radio", "Radio Volume", false, "%.1f"));   // "RADIO_VOL"
            AddFunction(new FlagValue(this, "37", "Radio Lights", "Radio A Light (white)", "True when indicator is lit", "%1d"));   // "RADIO_A_L"
            AddFunction(new FlagValue(this, "38", "Radio Lights", "Radio B Light (white)", "True when indicator is lit", "%1d"));   // "RADIO_B_L"
            AddFunction(new FlagValue(this, "39", "Radio Lights", "Radio C Light (white)", "True when indicator is lit", "%1d"));   // "RADIO_C_L"
            AddFunction(new FlagValue(this, "40", "Radio Lights", "Radio D Light (white)", "True when indicator is lit", "%1d"));   // "RADIO_D_L"
            AddFunction(new FlagValue(this, "41", "Radio Lights", "Radio TX Light (white)", "True when indicator is lit", "%1d"));   // "RADIO_TX_L"
            AddFunction(new Axis(this, "3", "3030", "25", 0.1d, 0d, 1d, "Throttle Quadrant", "Throttle Friction", false, "%.1f"));   // "THROTTLE_FRICTION"
            AddFunction(new Axis(this, "3", "3020", "288", 0.1d, 0d, 1d, "Throttle Quadrant", "Throttles Control L", false, "%.1f"));   // "THROTTLE_CONTROL_L"
            AddFunction(new Axis(this, "3", "3016", "18", 0.1d, 0d, 1d, "Throttle Quadrant", "Throttles Transit L", false, "%.1f"));   // "THROTTLE_TRANSIT_L"
            AddFunction(new RotaryEncoder(this, "3", "3014", "20", 0.01d, "Throttle Quadrant", "Throttles Control L Trigger"));   // "THROTTLE_CONTROL_L_TRIG"
            AddFunction(new Axis(this, "3", "3023", "289", 0.1d, 0d, 1d, "Throttle Quadrant", "Throttles Control R", false, "%.1f"));   // "THROTTLE_CONTROL_R"
            AddFunction(new Axis(this, "3", "3017", "19", 0.1d, 0d, 1d, "Throttle Quadrant", "Throttles Transit R", false, "%.1f"));   // "THROTTLE_TRANSIT_R"
            AddFunction(new RotaryEncoder(this, "3", "3015", "21", 0.01d, "Throttle Quadrant", "Throttles Control R Trigger"));   // "THROTTLE_CONTROL_R_TRIG"
            AddFunction(new Axis(this, "3", "3033", "24", 0.1d, 0d, 1d, "Throttle Quadrant", "Propeller Friction", false, "%.1f"));   // "PROP_FRICTION"
            AddFunction(new Axis(this, "3", "3036", "22", 0.1d, 0d, 1d, "Throttle Quadrant", "Propeller Control L", false, "%.1f"));   // "PROP_CONTROL_L"
            AddFunction(new Axis(this, "3", "3039", "23", 0.1d, 0d, 1d, "Throttle Quadrant", "Propeller Control R", false, "%.1f"));   // "PROP_CONTROL_R"
            AddFunction(Switch.CreateToggleSwitch(this, "3", "3086", "27", "1", "Position 1", "0", "Position 2", "Throttle Quadrant", "Mixture Control", "%1d"));   // "MIXTURE"
            AddFunction(Switch.CreateToggleSwitch(this, "4", "3022", "26", "1", "Position 1", "0", "Position 2", "Throttle Quadrant", "Supercharger Gear Change Switch", "%1d"));   // "SUPERCHARGER"
            AddFunction(new PushButton(this, "2", "3072", "254", "Starboard Wall", "Door Handle", "%1d"));   // "DOOR_LOCK"
            AddFunction(Switch.CreateToggleSwitch(this, "2", "3073", "324", "1", "Position 1", "0", "Position 2", "Starboard Wall", "Door Jettison Handle", "%1d"));   // "DOOR_JETT"
            AddFunction(new Switch(this, "4", "160", SwitchPositions.Create(3, 0, 0.5, "3075", "Position ", "%.2f"), "Starboard Wall", "Down Ident Lights Switch", "%.2f"));   // "DN_IDENT_L_SW"
            AddFunction(Switch.CreateToggleSwitch(this, "4", "3078", "161", "1", "Position 1", "0", "Position 2", "Starboard Wall", "Camera Gun Switch", "%1d"));   // "CAM_GUN_SW"
            AddFunction(Switch.CreateToggleSwitch(this, "4", "3080", "162", "1", "Position 1", "0", "Position 2", "Starboard Wall", "Nav Lights Switch", "%1d"));   // "NAV_L_SW"
            AddFunction(Switch.CreateToggleSwitch(this, "4", "3082", "163", "1", "Position 1", "0", "Position 2", "Starboard Wall", "UV Lighting Switch", "%1d"));   // "UV_L_SW"
            AddFunction(Switch.CreateToggleSwitch(this, "4", "3084", "164", "1", "Position 1", "0", "Position 2", "Starboard Wall", "Pitot Head Switch", "%1d"));   // "PITOT_SW"
            AddFunction(Switch.CreateToggleSwitch(this, "4", "3086", "165", "1", "Position 1", "0", "Position 2", "Starboard Wall", "Fuel Pump Switch", "%1d"));   // "FUEL_PUMP_SW"
            AddFunction(Switch.CreateToggleSwitch(this, "4", "3051", "166", "1", "Position 1", "0", "Position 2", "Starboard Wall", "Reflector Sight Switch", "%1d"));   // "REFLECTOR_SIGHT_SW"
            AddFunction(new Switch(this, "4", "167", SwitchPositions.Create(3, 0, 0.5, "3048", "Position ", "%.2f"), "Starboard Wall", "Nav. Head Lamp Switch", "%.2f"));   // "NAV_HEAD_L_SW"
            AddFunction(Switch.CreateToggleSwitch(this, "4", "3088", "168", "1", "Position 1", "0", "Position 2", "Starboard Wall", "IFF Switch", "%1d"));   // "IFF_SW"
            AddFunction(Switch.CreateToggleSwitch(this, "4", "3036", "169", "1", "Position 1", "0", "Position 2", "Starboard Wall", "IFF Detonator Cover", "%1d"));   // "IFF_DESRUCT_CVR"
            AddFunction(new PushButton(this, "4", "3038", "170", "Starboard Wall", "IFF Detonator Left Switch", "%1d"));   // "IFF_DESRUCT_L_BTN"
            AddFunction(new PushButton(this, "4", "3039", "171", "Starboard Wall", "IFF Detonator Right Switch", "%1d"));   // "IFF_DESRUCT_R_BTN"
            AddFunction(Switch.CreateToggleSwitch(this, "4", "3040", "172", "1", "Position 1", "0", "Position 2", "Starboard Wall", "Extinguisher Switch Cover Port", "%1d"));   // "PORT_EXTG_CVR"
            AddFunction(new PushButton(this, "4", "3042", "173", "Starboard Wall", "Extinguisher Switch Port", "%1d"));   // "PORT_EXTG_BTN"
            AddFunction(Switch.CreateToggleSwitch(this, "4", "3043", "174", "1", "Position 1", "0", "Position 2", "Starboard Wall", "Extinguisher Switch Cover Starboard", "%1d"));   // "STBD_EXTG_CVR"
            AddFunction(new PushButton(this, "4", "3045", "175", "Starboard Wall", "Extinguisher Switch Starboard", "%1d"));   // "STBD_EXTG_BTN"
            AddFunction(new Axis(this, "4", "3033", "176", 0.1d, 0d, 1d, "Starboard Wall", "Windscreen Wiper Rheostat", false, "%.1f"));   // "WIPER_RT"
            AddFunction(Switch.CreateToggleSwitch(this, "4", "3046", "178", "1", "Position 1", "0", "Position 2", "Starboard Wall", "Resin Lights Switch", "%1d"));   // "RESIN_L_SW"
            AddFunction(new PushButton(this, "4", "3068", "157", "Starboard Wall", "Morse Key", "%1d"));   // "MORSE_KEY"
            AddFunction(new Switch(this, "4", "158", SwitchPositions.Create(3, 0, 0.5, "3069", "Position ", "%.2f"), "Starboard Wall", "Downward Lamp Mode Selector", "%.2f"));   // "DOWNWARD_LVR"
            AddFunction(new Switch(this, "4", "159", SwitchPositions.Create(3, 0, 0.5, "3072", "Position ", "%.2f"), "Starboard Wall", "Upward Lamp Mode Selector", "%.2f"));   // "UPWARD_LVR"
            AddFunction(Switch.CreateToggleSwitch(this, "2", "3055", "293", "1", "Position 1", "0", "Position 2", "Starboard Wall", "Oxygen High Pressure Valve", "%1d"));   // "OXY_H_PRESS_VALVE"
            AddFunction(Switch.CreateToggleSwitch(this, "16", "3003", "187", "1", "Position 1", "0", "Position 2", "Starboard Wall", "Oxygen Regulator Starboard", "%1d"));   // "STBD_OXY_VALVE"
            AddFunction(new Axis(this, "4", "3095", "303", 0.1d, 0d, 1d, "Port Wall", "Chart Table Flood Light Dimmer", false, "%.1f"));   // "CHART_L_DIM"
            AddFunction(Switch.CreateToggleSwitch(this, "31", "3001", "202", "1", "Position 1", "0", "Position 2", "Starboard Wall", "Aerial Winch  Brake Lever", "%1d"));   // "AERIAL_BRAKE"
            AddFunction(new RotaryEncoder(this, "31", "3004", "356", 0.01d, "Starboard Wall", "Aerial Winch Rotary Handle"));   // "AERIAL_WINCH"
            AddFunction(new PushButton(this, "31", "3005", "357", "Starboard Wall", "Aerial Winch Reel Lock", "%1d"));   // "AERIAL_REEL"
            AddFunction(Switch.CreateToggleSwitch(this, "4", "3113", "307", "1", "Position 1", "0", "Position 2", "Starboard Wall", "Transmitter TypeF Switch", "%1d"));   // "TRANS_TYPF_SW"
            AddFunction(Switch.CreateToggleSwitch(this, "28", "3001", "305", "1", "Position 1", "0", "Position 2", "Starboard Wall", "T.1154 R.1155 L.T. Power Unit Switch", "%1d"));   // "LT_T1154_PW"
            AddFunction(Switch.CreateToggleSwitch(this, "28", "3003", "306", "1", "Position 1", "0", "Position 2", "Starboard Wall", "T.1154 R.1155 H.T. Power Unit Switch", "%1d"));   // "HT_T1154_PW"
            AddFunction(new FlagValue(this, "177", "Starboard Wall Lights", "Generator Warning Light (red)", "True when indicator is lit", "%1d"));   // "GEN_WARN_L"
            AddFunction(Switch.CreateToggleSwitch(this, "3", "3071", "192", "1", "Position 1", "0", "Position 2", "Lower Fuselage Part", "Engine Cut-Out Handle Port", "%1d"));   // "PORT_CUT-OUT"
            AddFunction(Switch.CreateToggleSwitch(this, "3", "3095", "191", "1", "Position 1", "0", "Position 2", "Lower Fuselage Part", "Engine Cut-Out Handle Starboard", "%1d"));   // "STBD_CUT-OUT"
            AddFunction(Switch.CreateThreeWaySwitch(this, "3", "193", "3073", "1", "Position 1", "0", "Position 2", "-1", "Position 3", "Lower Fuselage Part", "Fuel Cock Port", "%1d"));   // "PORT_FUEL_COCK"
            AddFunction(Switch.CreateThreeWaySwitch(this, "3", "194", "3076", "1", "Position 1", "0", "Position 2", "-1", "Position 3", "Lower Fuselage Part", "Fuel Cock Starboard", "%1d"));   // "STBD_FUEL_COCK"
            AddFunction(Switch.CreateToggleSwitch(this, "3", "3079", "195", "1", "Position 1", "0", "Position 2", "Lower Fuselage Part", "Transfer Fuel Cock", "%1d"));   // "TRANSFER_COCK-OUT"
            AddFunction(new PushButton(this, "3", "3050", "197", "Lower Fuselage Part", "Oil Dilution Switch Port", "%1d"));   // "PORT_OIL_DILUTION"
            AddFunction(new PushButton(this, "3", "3051", "198", "Lower Fuselage Part", "Oil Dilution Switch Starboard", "%1d"));   // "STBD_OIL_DILUTION"
            AddFunction(Switch.CreateToggleSwitch(this, "3", "3089", "196", "1", "Position 1", "0", "Position 2", "Lower Fuselage Part", "Tank Pressurizing Lever", "%1d"));   // "TANK_PRESS"
            AddFunction(Switch.CreateToggleSwitch(this, "3", "3091", "200", "1", "Position 1", "0", "Position 2", "Lower Fuselage Part", "Auxiliary Oil Supply Lever Port", "%1d"));   // "PORT_OIL_SUPPLY"
            AddFunction(Switch.CreateToggleSwitch(this, "3", "3093", "199", "1", "Position 1", "0", "Position 2", "Lower Fuselage Part", "Auxiliary Oil Supply Lever Starboard", "%1d"));   // "STBD_OIL_SUPPLY"
            AddFunction(Switch.CreateToggleSwitch(this, "2", "3057", "203", "1", "Position 1", "0", "Position 2", "Lower Fuselage Part", "Cabin Heater Control", "%1d"));   // "CABIN_HEATER_LVR"
            AddFunction(Switch.CreateToggleSwitch(this, "2", "3059", "204", "1", "Position 1", "0", "Position 2", "Lower Fuselage Part", "Gun Heater Control", "%1d"));   // "GUN_HEATER_LVR"
            AddFunction(Switch.CreateToggleSwitch(this, "2", "3020", "256", "1", "Position 1", "0", "Position 2", "Lower Fuselage Part", "Arm Rest Port", "%1d"));   // "PORT_ARMREST"
            AddFunction(Switch.CreateToggleSwitch(this, "2", "3061", "257", "1", "Position 1", "0", "Position 2", "Lower Fuselage Part", "Arm Rest Starboard", "%1d"));   // "STBD_ARMREST"
            AddFunction(Switch.CreateToggleSwitch(this, "5", "3043", "323", "1", "Position 1", "0", "Position 2", "Lower Fuselage Part", "Harness Lever", "%1d"));   // "HARNESS_LVR"
            AddFunction(Switch.CreateToggleSwitch(this, "2", "3069", "333", "1", "Position 1", "0", "Position 2", "Lower Fuselage Part", "Hydraulic Select", "%1d"));   // "HYDR_SEL"
            AddFunction(new Axis(this, "4", "3101", "302", 0.1d, 0d, 1d, "Quarter", "Roof Dome Light Dimmer", false, "%.1f"));   // "DOME_L_DIM"
            AddFunction(new Axis(this, "4", "3092", "17", 0.1d, 0d, 1d, "Quarter", "Loop Antenna Flood Light Dimmer", false, "%.1f"));   // "LOOP_ANT_L_DIM"
            AddFunction(new Switch(this, "25", "224", SwitchPositions.Create(5, -1, 0.5, "3059", "Position ", "%.2f"), "Quarter", "Aerial Selector Switch Type J", "%.2f"));   // "TYPE_J_SEL"
            AddFunction(Switch.CreateToggleSwitch(this, "25", "3107", "241", "1", "Position 1", "0", "Position 2", "Quarter", "Loop Antenna Lock", "%1d"));   // "LOOP_ANT_LOCK"
            AddFunction(new RotaryEncoder(this, "25", "3094", "240", 0.01d, "Quarter", "Loop Antenna Scale"));   // "LOOP_ANT_SCALE"
            AddFunction(new Switch(this, "4", "188", SwitchPositions.Create(6, 0, 0.2, "3104", "Position ", "%.2f"), "Quarter", "IFF Channel Switch", "%.2f"));   // "IFF_CHAN"
            AddFunction(Switch.CreateToggleSwitch(this, "4", "3107", "363", "1", "Position 1", "0", "Position 2", "Quarter", "IFF Detonate Switch Cover", "%1d"));   // "IFF_DETONATE_CVR"
            AddFunction(Switch.CreateToggleSwitch(this, "4", "3109", "189", "1", "Position 1", "0", "Position 2", "Quarter", "IFF Detonate Switch", "%1d"));   // "IFF_DETONATE"
            AddFunction(Switch.CreateToggleSwitch(this, "4", "3111", "190", "1", "Position 1", "0", "Position 2", "Quarter", "IFF Power Switch", "%1d"));   // "IFF_PW"
            AddFunction(new FlagValue(this, "276", "Quarter Lights", "Dome Lamp (white)", "True when indicator is lit", "%1d"));   // "DOME_LAMP_L"
            AddFunction(new FlagValue(this, "275", "Quarter Lights", "Antenna Lamp (white)", "True when indicator is lit", "%1d"));   // "LOOP_ANT_LAMP_L"
            AddFunction(new PushButton(this, "25", "3001", "365", "T1154", "T.1154 Key", "%1d"));   // "T1154_KEY"
            AddFunction(new RotaryEncoder(this, "25", "3002", "358", 0.01d, "T1154", "T.1154 Master Oscillator Tuning Condenser C2"));   // "T1154_C2"
            AddFunction(new RotaryEncoder(this, "25", "3005", "359", 0.01d, "T1154", "T.1154 Master Oscillator Tuning Condenser C4"));   // "T1154_C4"
            AddFunction(new RotaryEncoder(this, "25", "3008", "360", 0.01d, "T1154", "T.1154 Output Tuning Condenser C15"));   // "T1154_C15"
            AddFunction(new RotaryEncoder(this, "25", "3011", "361", 0.01d, "T1154", "T.1154 Output Tuning Condenser C16"));   // "T1154_C16"
            AddFunction(new RotaryEncoder(this, "25", "3014", "362", 0.01d, "T1154", "T.1154 Master Oscillator Tuning Condenser C17"));   // "T1154_C17"
            AddFunction(new Switch(this, "25", "212", SwitchPositions.Create(8, 0, 0.1, "3017", "Position ", "%.2f"), "T1154", "T.1154 Condenser C2 Presets Knob", "%.2f"));   // "T1154_C2_B"
            AddFunction(new Switch(this, "25", "211", SwitchPositions.Create(8, 0, 0.1, "3020", "Position ", "%.2f"), "T1154", "T.1154 Condenser C4 Presets Knob", "%.2f"));   // "T1154_C4_B"
            AddFunction(new Switch(this, "25", "213", SwitchPositions.Create(8, 0, 0.1, "3023", "Position ", "%.2f"), "T1154", "T.1154 Condenser C15 Presets Knob", "%.2f"));   // "T1154_C15_B"
            AddFunction(new Switch(this, "25", "214", SwitchPositions.Create(8, 0, 0.1, "3026", "Position ", "%.2f"), "T1154", "T.1154 Condenser C16 Presets Knob", "%.2f"));   // "T1154_C16_B"
            AddFunction(new Switch(this, "25", "210", SwitchPositions.Create(8, 0, 0.1, "3029", "Position ", "%.2f"), "T1154", "T.1154 Condenser C17 Presets Knob", "%.2f"));   // "T1154_C17_B"
            AddFunction(new Axis(this, "25", "3032", "223", 0.1d, -1d, 1d, "T1154", "T.1154 Master Oscillator C2 Vernier", false, "%.1f"));   // "T1154_C2_V"
            AddFunction(new Axis(this, "25", "3035", "222", 0.1d, -1d, 1d, "T1154", "T.1154 Master Oscillator C4 Vernier", false, "%.1f"));   // "T1154_C4_V"
            AddFunction(new Switch(this, "25", "215", SwitchPositions.Create(3, 0.0, 0.1, "3038", "Position ", "%.2f"), "T1154", "T.1154 Frequency Range Switch S1 S2", "%.2f"));   // "T1154"
            AddFunction(new Switch(this, "25", "216", SwitchPositions.Create(9, 0.0, 0.1, "3041", "Position ", "%.2f"), "T1154", "T.1154 Inductance Tapping Switch S3", "%.2f"));   // "T1154"
            AddFunction(new Switch(this, "25", "217", SwitchPositions.Create(9, 0.0, 0.1, "3044", "Position ", "%.2f"), "T1154", "T.1154 Inductance Tapping Switch S4", "%.2f"));   // "T1154"
            AddFunction(new Switch(this, "25", "218", SwitchPositions.Create(6, 0.0, 0.1, "3047", "Position ", "%.2f"), "T1154", "T.1154 Master Switch S5", "%.2f"));   // "T1154"
            AddFunction(new Switch(this, "25", "219", SwitchPositions.Create(17, 0.0, 0.05, "3050", "Position ", "%.2f"), "T1154", "T.1154 Inductance Tapping Switch S6", "%.2f"));   // "T1154"
            AddFunction(new Switch(this, "25", "220", SwitchPositions.Create(17, 0.0, 0.05, "3053", "Position ", "%.2f"), "T1154", "T.1154 Inductance Tapping Switch S7", "%.2f"));   // "T1154"
            AddFunction(new Axis(this, "25", "3056", "221", 0.1d, 0d, 1d, "T1154", "T.1154 Output Inductance Control L6", false, "%.1f"));   // "T1154_L6"
            AddFunction(new NetworkValue(this, "207", "T1154 Gauges", "T.1154 C2 Gauge", "", "Numeric Value between 0.0 and 0.937", BindingValueUnits.Numeric));   // "T1154_C2_G"
            AddFunction(new NetworkValue(this, "206", "T1154 Gauges", "T.1154 C4 Gauge", "", "Numeric Value between 0.0 and 0.912", BindingValueUnits.Numeric));   // "T1154_C4_G"
            AddFunction(new NetworkValue(this, "208", "T1154 Gauges", "T.1154 C15 Gauge", "", "Numeric Value between 0.0 and 0.937", BindingValueUnits.Numeric));   // "T1154_C15_G"
            AddFunction(new NetworkValue(this, "209", "T1154 Gauges", "T.1154 C16 Gauge", "", "Numeric Value between 0.0 and 0.912", BindingValueUnits.Numeric));   // "T1154_C16_G"
            AddFunction(new NetworkValue(this, "205", "T1154 Gauges", "T.1154 C17 Gauge", "", "Numeric Value between 0.0 and 0.912", BindingValueUnits.Numeric));   // "T1154_C17_G"
            AddFunction(new NetworkValue(this, "104", "T1154 Gauges", "T.1154 M1 Gauge", "", "Numeric Value between 0 and 1", BindingValueUnits.Numeric));   // "T1154_M1_G"
            AddFunction(new NetworkValue(this, "105", "T1154 Gauges", "T.1154 M2 Gauge", "", "Numeric Value between 0 and 1", BindingValueUnits.Numeric));   // "T1154_M2_G"
            AddFunction(new NetworkValue(this, "106", "T1154 Gauges", "T.1154 M3 Gauge", "", "Numeric Value between 0 and 1", BindingValueUnits.Numeric));   // "T1154_M3_G"
            AddFunction(new Switch(this, "25", "238", SwitchPositions.Create(5, 0.0, 0.1, "3062", "Position ", "%.2f"), "R1155", "R.1155 Master Selector Switch", "%.2f"));   // "R1155"
            AddFunction(new Switch(this, "25", "231", SwitchPositions.Create(5, 0.0, 0.1, "3065", "Position ", "%.2f"), "R1155", "R.1155 Frequency Range Switch", "%.2f"));   // "R1155"
            AddFunction(new Axis(this, "25", "3068", "229", 0.1d, 0d, 1d, "R1155", "R.1155 Volume Knob", false, "%.1f"));   // "R1155_VOL"
            AddFunction(new Axis(this, "25", "3071", "233", 0.1d, 0d, 1d, "R1155", "R.1155 Tuning (Fine)", false, "%.1f"));   // "R1155_RANGE_HIGH"
            AddFunction(new Axis(this, "25", "3074", "234", 0.1d, 0d, 1d, "R1155", "R.1155 Tuning (Coarse)", false, "%.1f"));   // "R1155_RANGE_LOW"
            AddFunction(Switch.CreateToggleSwitch(this, "25", "3077", "230", "1", "Position 1", "0", "Position 2", "R1155", "R.1155 Heterodyne Switch", "%1d"));   // "R1155_HETI"
            AddFunction(new Axis(this, "25", "3079", "225", 0.1d, -1d, 1d, "R1155", "R.1155 Meter Balance Knob", false, "%.1f"));   // "R1155_METER_BAL"
            AddFunction(Switch.CreateToggleSwitch(this, "25", "3082", "226", "1", "Position 1", "0", "Position 2", "R1155", "R.1155 Filter Switch", "%1d"));   // "R1155_FILTER"
            AddFunction(new Axis(this, "25", "3084", "227", 0.1d, 0d, 1d, "R1155", "R.1155 Meter Amplitude Knob", false, "%.1f"));   // "R1155_METER_AMP"
            AddFunction(Switch.CreateToggleSwitch(this, "25", "3087", "235", "1", "Position 1", "0", "Position 2", "R1155", "R.1155 Meter Deflection Sensitivity Switch", "%1d"));   // "R1155_METER_DEF"
            AddFunction(Switch.CreateThreeWaySwitch(this, "25", "236", "3089", "1", "Position 1", "0", "Position 2", "-1", "Position 3", "R1155", "R.1155 Aural Sense Switch", "%1d"));   // "R1155_AURAL_SENSE"
            AddFunction(Switch.CreateToggleSwitch(this, "25", "3090", "237", "1", "Position 1", "0", "Position 2", "R1155", "R.1155 Meter Frequency Switch", "%1d"));   // "R1155_SW_SPEED"
            AddFunction(new NetworkValue(this, "232", "R1155 Gauges", "R.1155 Tuner Gauge", "", "Numeric Value between 0 and 1", BindingValueUnits.Numeric));   // "R1155_TUNER_G"
            AddFunction(new NetworkValue(this, "239", "R1155 Gauges", "R.1155 Tuning Cathode Gauge", "", "Numeric Value between 0 and 1", BindingValueUnits.Numeric));   // "R1155_TUNE_CAT_G"
            AddFunction(new NetworkValue(this, "228", "R1155 Gauges", "R.1155 Tuning Anode Gauge", "", "Numeric Value between 0 and 1", BindingValueUnits.Numeric));   // "R1155_TUNE_ANO_G"
            AddFunction(new NetworkValue(this, "88", "R1155 Gauges", "R.1155 DFLH Gauge", "", "Numeric Value between -1 and 1", BindingValueUnits.Numeric));   // "R1155_DFLH_G"
            AddFunction(new NetworkValue(this, "89", "R1155 Gauges", "R.1155 DFRH Gauge", "", "Numeric Value between -1 and 1", BindingValueUnits.Numeric));   // "R1155_DFRH_G"
            AddFunction(new NetworkValue(this, "255", "Cockpit", "Cockpit Hatch Position", "", "Numeric Value between 0 and 1", BindingValueUnits.Numeric));   // "COCKPIT_HATCH"
            AddFunction(new FlagValue(this, "308", "Cockpit Lights", "Transmitter TypeF Light (yellow)", "True when indicator is lit", "%1d"));   // "TRANS_TYPF_L"
            AddFunction(new FlagValue(this, "379", "Cockpit Lights", "Left Red Lamp (red)", "True when indicator is lit", "%1d"));   // "RED_LAMP_L_L"
            AddFunction(new FlagValue(this, "301", "Cockpit Lights", "Right White Lamp (white)", "True when indicator is lit", "%1d"));   // "WH_LAMP_R_L"
            AddFunction(new FlagValue(this, "300", "Cockpit Lights", "Front White Lamp (white)", "True when indicator is lit", "%1d"));   // "WH_LAMP_F_L"
            AddFunction(new FlagValue(this, "299", "Cockpit Lights", "Left White Lamp (white)", "True when indicator is lit", "%1d"));   // "WH_LAMP_L_L"
            AddFunction(new FlagValue(this, "297", "Cockpit Lights", "Gauges Glow (green)", "True when indicator is lit", "%1d"));   // "GAUGES_GLOW_L"
            AddFunction(new FlagValue(this, "77", "Main Panel Lights", "Under Carriage Left UP Light (red)", "True when indicator is lit", "%1d"));   // "GEAR_UP_L_L"
            AddFunction(new FlagValue(this, "79", "Main Panel Lights", "Under Carriage Right UP Light (red)", "True when indicator is lit", "%1d"));   // "GEAR_UP_R_L"
            AddFunction(new FlagValue(this, "78", "Main Panel Lights", "Under Carriage Left DOWN Light (green)", "True when indicator is lit", "%1d"));   // "GEAR_DN_L_L"
            AddFunction(new FlagValue(this, "80", "Main Panel Lights", "Under Carriage Right DOWN Light (green)", "True when indicator is lit", "%1d"));   // "GEAR_DN_R_L"
        }
    }
}
